// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: pb/proto/account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRes_Result int32

const (
	RegisterRes_Success      RegisterRes_Result = 0 //成功
	RegisterRes_EmptyInput   RegisterRes_Result = 1 //账号或密码为空
	RegisterRes_PwdUnequal   RegisterRes_Result = 2 //两次密码不同
	RegisterRes_AccountExist RegisterRes_Result = 3 //账号已存在
	RegisterRes_DbError      RegisterRes_Result = 4 //数据库错误
)

// Enum value maps for RegisterRes_Result.
var (
	RegisterRes_Result_name = map[int32]string{
		0: "Success",
		1: "EmptyInput",
		2: "PwdUnequal",
		3: "AccountExist",
		4: "DbError",
	}
	RegisterRes_Result_value = map[string]int32{
		"Success":      0,
		"EmptyInput":   1,
		"PwdUnequal":   2,
		"AccountExist": 3,
		"DbError":      4,
	}
)

func (x RegisterRes_Result) Enum() *RegisterRes_Result {
	p := new(RegisterRes_Result)
	*p = x
	return p
}

func (x RegisterRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_account_proto_enumTypes[0].Descriptor()
}

func (RegisterRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_account_proto_enumTypes[0]
}

func (x RegisterRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterRes_Result.Descriptor instead.
func (RegisterRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{4, 0}
}

type LoginRes_Result int32

const (
	LoginRes_Success    LoginRes_Result = 0 //成功
	LoginRes_AccountErr LoginRes_Result = 1 //账号不存在或密码错误
	LoginRes_Logged     LoginRes_Result = 2 //已登陆
)

// Enum value maps for LoginRes_Result.
var (
	LoginRes_Result_name = map[int32]string{
		0: "Success",
		1: "AccountErr",
		2: "Logged",
	}
	LoginRes_Result_value = map[string]int32{
		"Success":    0,
		"AccountErr": 1,
		"Logged":     2,
	}
)

func (x LoginRes_Result) Enum() *LoginRes_Result {
	p := new(LoginRes_Result)
	*p = x
	return p
}

func (x LoginRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_account_proto_enumTypes[1].Descriptor()
}

func (LoginRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_account_proto_enumTypes[1]
}

func (x LoginRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginRes_Result.Descriptor instead.
func (LoginRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{5, 0}
}

type AccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//
	//	*AccountReq_RegisterReq
	//	*AccountReq_LoginReq
	Req isAccountReq_Req `protobuf_oneof:"req"`
}

func (x *AccountReq) Reset() {
	*x = AccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReq) ProtoMessage() {}

func (x *AccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReq.ProtoReflect.Descriptor instead.
func (*AccountReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{0}
}

func (m *AccountReq) GetReq() isAccountReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *AccountReq) GetRegisterReq() *RegisterReq {
	if x, ok := x.GetReq().(*AccountReq_RegisterReq); ok {
		return x.RegisterReq
	}
	return nil
}

func (x *AccountReq) GetLoginReq() *LoginReq {
	if x, ok := x.GetReq().(*AccountReq_LoginReq); ok {
		return x.LoginReq
	}
	return nil
}

type isAccountReq_Req interface {
	isAccountReq_Req()
}

type AccountReq_RegisterReq struct {
	RegisterReq *RegisterReq `protobuf:"bytes,1,opt,name=register_req,json=registerReq,proto3,oneof"` //注册请求
}

type AccountReq_LoginReq struct {
	LoginReq *LoginReq `protobuf:"bytes,2,opt,name=login_req,json=loginReq,proto3,oneof"` //登陆
}

func (*AccountReq_RegisterReq) isAccountReq_Req() {}

func (*AccountReq_LoginReq) isAccountReq_Req() {}

type AccountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//
	//	*AccountRes_RegisterRes
	//	*AccountRes_LoginRes
	Res isAccountRes_Res `protobuf_oneof:"res"`
}

func (x *AccountRes) Reset() {
	*x = AccountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRes) ProtoMessage() {}

func (x *AccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRes.ProtoReflect.Descriptor instead.
func (*AccountRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{1}
}

func (m *AccountRes) GetRes() isAccountRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *AccountRes) GetRegisterRes() *RegisterRes {
	if x, ok := x.GetRes().(*AccountRes_RegisterRes); ok {
		return x.RegisterRes
	}
	return nil
}

func (x *AccountRes) GetLoginRes() *LoginRes {
	if x, ok := x.GetRes().(*AccountRes_LoginRes); ok {
		return x.LoginRes
	}
	return nil
}

type isAccountRes_Res interface {
	isAccountRes_Res()
}

type AccountRes_RegisterRes struct {
	RegisterRes *RegisterRes `protobuf:"bytes,1,opt,name=register_res,json=registerRes,proto3,oneof"` //注册响应
}

type AccountRes_LoginRes struct {
	LoginRes *LoginRes `protobuf:"bytes,2,opt,name=login_res,json=loginRes,proto3,oneof"` //登陆响应
}

func (*AccountRes_RegisterRes) isAccountRes_Res() {}

func (*AccountRes_LoginRes) isAccountRes_Res() {}

// ////////////////////////////////////////
type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"passport"
	Passport string `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport"`
	// @inject_tag: json:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	// @inject_tag: json:"password1"
	Password1 string `protobuf:"bytes,3,opt,name=password1,proto3" json:"password1"`
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetPassword1() string {
	if x != nil {
		return x.Password1
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"passport"
	Passport string `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport"`
	// @inject_tag: json:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// ///////////////////////////////////////
type RegisterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result RegisterRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.RegisterRes_Result" json:"result"`
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRes) GetResult() RegisterRes_Result {
	if x != nil {
		return x.Result
	}
	return RegisterRes_Success
}

type LoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result LoginRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.LoginRes_Result" json:"result"`
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"` //账号Id
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_account_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRes) GetResult() LoginRes_Result {
	if x != nil {
		return x.Result
	}
	return LoginRes_Success
}

func (x *LoginRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_pb_proto_account_proto protoreflect.FileDescriptor

var file_pb_proto_account_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x76, 0x0a, 0x0a,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x34, 0x0a, 0x0c, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x2b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x42, 0x05, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x22, 0x76, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x34, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x22, 0x63, 0x0a, 0x0b,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x31,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x31, 0x22, 0x42, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x54, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x77, 0x64, 0x55, 0x6e, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x44, 0x62, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x22, 0x83, 0x01, 0x0a, 0x08,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x31,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x45, 0x72, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x10,
	0x02, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_account_proto_rawDescOnce sync.Once
	file_pb_proto_account_proto_rawDescData = file_pb_proto_account_proto_rawDesc
)

func file_pb_proto_account_proto_rawDescGZIP() []byte {
	file_pb_proto_account_proto_rawDescOnce.Do(func() {
		file_pb_proto_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_account_proto_rawDescData)
	})
	return file_pb_proto_account_proto_rawDescData
}

var file_pb_proto_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_proto_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_proto_account_proto_goTypes = []interface{}{
	(RegisterRes_Result)(0), // 0: pb.RegisterRes.Result
	(LoginRes_Result)(0),    // 1: pb.LoginRes.Result
	(*AccountReq)(nil),      // 2: pb.AccountReq
	(*AccountRes)(nil),      // 3: pb.AccountRes
	(*RegisterReq)(nil),     // 4: pb.RegisterReq
	(*LoginReq)(nil),        // 5: pb.LoginReq
	(*RegisterRes)(nil),     // 6: pb.RegisterRes
	(*LoginRes)(nil),        // 7: pb.LoginRes
}
var file_pb_proto_account_proto_depIdxs = []int32{
	4, // 0: pb.AccountReq.register_req:type_name -> pb.RegisterReq
	5, // 1: pb.AccountReq.login_req:type_name -> pb.LoginReq
	6, // 2: pb.AccountRes.register_res:type_name -> pb.RegisterRes
	7, // 3: pb.AccountRes.login_res:type_name -> pb.LoginRes
	0, // 4: pb.RegisterRes.result:type_name -> pb.RegisterRes.Result
	1, // 5: pb.LoginRes.result:type_name -> pb.LoginRes.Result
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_proto_account_proto_init() }
func file_pb_proto_account_proto_init() {
	if File_pb_proto_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_proto_account_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AccountReq_RegisterReq)(nil),
		(*AccountReq_LoginReq)(nil),
	}
	file_pb_proto_account_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AccountRes_RegisterRes)(nil),
		(*AccountRes_LoginRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_account_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_proto_account_proto_goTypes,
		DependencyIndexes: file_pb_proto_account_proto_depIdxs,
		EnumInfos:         file_pb_proto_account_proto_enumTypes,
		MessageInfos:      file_pb_proto_account_proto_msgTypes,
	}.Build()
	File_pb_proto_account_proto = out.File
	file_pb_proto_account_proto_rawDesc = nil
	file_pb_proto_account_proto_goTypes = nil
	file_pb_proto_account_proto_depIdxs = nil
}
