// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: pb/proto/config.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//
	//	*ConfigReq_GetDischargeReq
	//	*ConfigReq_GetCommodityReq
	//	*ConfigReq_GetGiftReq
	//	*ConfigReq_GetsBuildConfReq
	//	*ConfigReq_GetsSoulReq
	Req isConfigReq_Req `protobuf_oneof:"req"`
}

func (x *ConfigReq) Reset() {
	*x = ConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReq) ProtoMessage() {}

func (x *ConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigReq.ProtoReflect.Descriptor instead.
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{0}
}

func (m *ConfigReq) GetReq() isConfigReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *ConfigReq) GetGetDischargeReq() *GetDischargeReq {
	if x, ok := x.GetReq().(*ConfigReq_GetDischargeReq); ok {
		return x.GetDischargeReq
	}
	return nil
}

func (x *ConfigReq) GetGetCommodityReq() *GetCommodityReq {
	if x, ok := x.GetReq().(*ConfigReq_GetCommodityReq); ok {
		return x.GetCommodityReq
	}
	return nil
}

func (x *ConfigReq) GetGetGiftReq() *GetGiftReq {
	if x, ok := x.GetReq().(*ConfigReq_GetGiftReq); ok {
		return x.GetGiftReq
	}
	return nil
}

func (x *ConfigReq) GetGetsBuildConfReq() *GetsBuildConfReq {
	if x, ok := x.GetReq().(*ConfigReq_GetsBuildConfReq); ok {
		return x.GetsBuildConfReq
	}
	return nil
}

func (x *ConfigReq) GetGetsSoulReq() *GetsSoulReq {
	if x, ok := x.GetReq().(*ConfigReq_GetsSoulReq); ok {
		return x.GetsSoulReq
	}
	return nil
}

type isConfigReq_Req interface {
	isConfigReq_Req()
}

type ConfigReq_GetDischargeReq struct {
	GetDischargeReq *GetDischargeReq `protobuf:"bytes,1,opt,name=get_discharge_req,json=getDischargeReq,proto3,oneof"` //获取充值信息
}

type ConfigReq_GetCommodityReq struct {
	GetCommodityReq *GetCommodityReq `protobuf:"bytes,2,opt,name=get_commodity_req,json=getCommodityReq,proto3,oneof"` //获取商品
}

type ConfigReq_GetGiftReq struct {
	GetGiftReq *GetGiftReq `protobuf:"bytes,3,opt,name=get_gift_req,json=getGiftReq,proto3,oneof"` //获取礼包
}

type ConfigReq_GetsBuildConfReq struct {
	GetsBuildConfReq *GetsBuildConfReq `protobuf:"bytes,4,opt,name=gets_build_conf_req,json=getsBuildConfReq,proto3,oneof"` //获取建筑设施
}

type ConfigReq_GetsSoulReq struct {
	GetsSoulReq *GetsSoulReq `protobuf:"bytes,5,opt,name=gets_soul_req,json=getsSoulReq,proto3,oneof"` //获取契约技能
}

func (*ConfigReq_GetDischargeReq) isConfigReq_Req() {}

func (*ConfigReq_GetCommodityReq) isConfigReq_Req() {}

func (*ConfigReq_GetGiftReq) isConfigReq_Req() {}

func (*ConfigReq_GetsBuildConfReq) isConfigReq_Req() {}

func (*ConfigReq_GetsSoulReq) isConfigReq_Req() {}

type ConfigRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//
	//	*ConfigRes_GetDischargeRes
	//	*ConfigRes_GetCommodityRes
	//	*ConfigRes_GetGiftRes
	//	*ConfigRes_GetsBuildConfRes
	//	*ConfigRes_GetsSoulRes
	Res isConfigRes_Res `protobuf_oneof:"res"`
}

func (x *ConfigRes) Reset() {
	*x = ConfigRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRes) ProtoMessage() {}

func (x *ConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRes.ProtoReflect.Descriptor instead.
func (*ConfigRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{1}
}

func (m *ConfigRes) GetRes() isConfigRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *ConfigRes) GetGetDischargeRes() *GetDischargeRes {
	if x, ok := x.GetRes().(*ConfigRes_GetDischargeRes); ok {
		return x.GetDischargeRes
	}
	return nil
}

func (x *ConfigRes) GetGetCommodityRes() *GetCommodityRes {
	if x, ok := x.GetRes().(*ConfigRes_GetCommodityRes); ok {
		return x.GetCommodityRes
	}
	return nil
}

func (x *ConfigRes) GetGetGiftRes() *GetGiftRes {
	if x, ok := x.GetRes().(*ConfigRes_GetGiftRes); ok {
		return x.GetGiftRes
	}
	return nil
}

func (x *ConfigRes) GetGetsBuildConfRes() *GetsBuildConfRes {
	if x, ok := x.GetRes().(*ConfigRes_GetsBuildConfRes); ok {
		return x.GetsBuildConfRes
	}
	return nil
}

func (x *ConfigRes) GetGetsSoulRes() *GetsSoulRes {
	if x, ok := x.GetRes().(*ConfigRes_GetsSoulRes); ok {
		return x.GetsSoulRes
	}
	return nil
}

type isConfigRes_Res interface {
	isConfigRes_Res()
}

type ConfigRes_GetDischargeRes struct {
	GetDischargeRes *GetDischargeRes `protobuf:"bytes,1,opt,name=get_discharge_res,json=getDischargeRes,proto3,oneof"` //获取充值信息
}

type ConfigRes_GetCommodityRes struct {
	GetCommodityRes *GetCommodityRes `protobuf:"bytes,2,opt,name=get_commodity_res,json=getCommodityRes,proto3,oneof"` //获取商品
}

type ConfigRes_GetGiftRes struct {
	GetGiftRes *GetGiftRes `protobuf:"bytes,3,opt,name=get_gift_res,json=getGiftRes,proto3,oneof"` //获取礼包
}

type ConfigRes_GetsBuildConfRes struct {
	GetsBuildConfRes *GetsBuildConfRes `protobuf:"bytes,4,opt,name=gets_build_conf_res,json=getsBuildConfRes,proto3,oneof"` //获取建筑设施
}

type ConfigRes_GetsSoulRes struct {
	GetsSoulRes *GetsSoulRes `protobuf:"bytes,5,opt,name=gets_soul_res,json=getsSoulRes,proto3,oneof"` //获取契约技能
}

func (*ConfigRes_GetDischargeRes) isConfigRes_Res() {}

func (*ConfigRes_GetCommodityRes) isConfigRes_Res() {}

func (*ConfigRes_GetGiftRes) isConfigRes_Res() {}

func (*ConfigRes_GetsBuildConfRes) isConfigRes_Res() {}

func (*ConfigRes_GetsSoulRes) isConfigRes_Res() {}

// //////////////////////////////////
type GetDischargeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDischargeReq) Reset() {
	*x = GetDischargeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDischargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDischargeReq) ProtoMessage() {}

func (x *GetDischargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDischargeReq.ProtoReflect.Descriptor instead.
func (*GetDischargeReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{2}
}

type GetCommodityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	// @inject_tag: json:"shop_id"
	ShopId int32 `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id"` //商店ID(0-代表所有商店）
	// @inject_tag: json:"type"
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type"` // 0-全部,1-物品,2-装备,3-特殊
}

func (x *GetCommodityReq) Reset() {
	*x = GetCommodityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommodityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommodityReq) ProtoMessage() {}

func (x *GetCommodityReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommodityReq.ProtoReflect.Descriptor instead.
func (*GetCommodityReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommodityReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommodityReq) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetCommodityReq) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *GetCommodityReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetGiftReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	// @inject_tag: json:"shop_id"
	ShopId int32 `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id"` //商店ID(0-代表所有商店）
}

func (x *GetGiftReq) Reset() {
	*x = GetGiftReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGiftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftReq) ProtoMessage() {}

func (x *GetGiftReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftReq.ProtoReflect.Descriptor instead.
func (*GetGiftReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetGiftReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGiftReq) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetGiftReq) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type GetsBuildConfReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	// @inject_tag: json:"type"
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type"` // 0-全部,1-基础设施，2-农业设施，3-工业设施
}

func (x *GetsBuildConfReq) Reset() {
	*x = GetsBuildConfReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsBuildConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsBuildConfReq) ProtoMessage() {}

func (x *GetsBuildConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsBuildConfReq.ProtoReflect.Descriptor instead.
func (*GetsBuildConfReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetsBuildConfReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetsBuildConfReq) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetsBuildConfReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetsSoulReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"soul_id"
	SoulId int32 `protobuf:"varint,1,opt,name=soul_id,json=soulId,proto3" json:"soul_id"`
}

func (x *GetsSoulReq) Reset() {
	*x = GetsSoulReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsSoulReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsSoulReq) ProtoMessage() {}

func (x *GetsSoulReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsSoulReq.ProtoReflect.Descriptor instead.
func (*GetsSoulReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{6}
}

func (x *GetsSoulReq) GetSoulId() int32 {
	if x != nil {
		return x.SoulId
	}
	return 0
}

// //////////////////////////////////
type GetDischargeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"discharges"
	Discharges []*Discharge `protobuf:"bytes,1,rep,name=discharges,proto3" json:"discharges"`
}

func (x *GetDischargeRes) Reset() {
	*x = GetDischargeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDischargeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDischargeRes) ProtoMessage() {}

func (x *GetDischargeRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDischargeRes.ProtoReflect.Descriptor instead.
func (*GetDischargeRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetDischargeRes) GetDischarges() []*Discharge {
	if x != nil {
		return x.Discharges
	}
	return nil
}

type GetCommodityRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	// @inject_tag: json:"total"
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	// @inject_tag: json:"shop_id"
	ShopId int32 `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id"` //商店ID(0-代表所有商店）
	// @inject_tag: json:"type"
	Type int32 `protobuf:"varint,5,opt,name=type,proto3" json:"type"` // 0-全部,1-装备，2-工具，3-消耗品，4-特殊
	// @inject_tag: json:"commodities"
	Commodities []*Commodity `protobuf:"bytes,6,rep,name=commodities,proto3" json:"commodities"`
}

func (x *GetCommodityRes) Reset() {
	*x = GetCommodityRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommodityRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommodityRes) ProtoMessage() {}

func (x *GetCommodityRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommodityRes.ProtoReflect.Descriptor instead.
func (*GetCommodityRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommodityRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommodityRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetCommodityRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCommodityRes) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *GetCommodityRes) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetCommodityRes) GetCommodities() []*Commodity {
	if x != nil {
		return x.Commodities
	}
	return nil
}

type GetGiftRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	// @inject_tag: json:"total"
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	// @inject_tag: json:"gifts"
	Gifts []*Gift `protobuf:"bytes,4,rep,name=gifts,proto3" json:"gifts"`
}

func (x *GetGiftRes) Reset() {
	*x = GetGiftRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGiftRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGiftRes) ProtoMessage() {}

func (x *GetGiftRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGiftRes.ProtoReflect.Descriptor instead.
func (*GetGiftRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{9}
}

func (x *GetGiftRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGiftRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetGiftRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetGiftRes) GetGifts() []*Gift {
	if x != nil {
		return x.Gifts
	}
	return nil
}

type GetsBuildConfRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	// @inject_tag: json:"total"
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	// @inject_tag: json:"type"
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type"` // 0-全部,1-基础设施，2-农业设施，3-工业设施
	// @inject_tag: json:"build_configs"
	BuildConfigs []*BuildConf `protobuf:"bytes,5,rep,name=build_configs,json=buildConfigs,proto3" json:"build_configs"`
}

func (x *GetsBuildConfRes) Reset() {
	*x = GetsBuildConfRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsBuildConfRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsBuildConfRes) ProtoMessage() {}

func (x *GetsBuildConfRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsBuildConfRes.ProtoReflect.Descriptor instead.
func (*GetsBuildConfRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{10}
}

func (x *GetsBuildConfRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetsBuildConfRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetsBuildConfRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetsBuildConfRes) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetsBuildConfRes) GetBuildConfigs() []*BuildConf {
	if x != nil {
		return x.BuildConfigs
	}
	return nil
}

type GetsSoulRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"cd"
	Cd int32 `protobuf:"varint,1,opt,name=cd,proto3" json:"cd"` //冷却回合
	// @inject_tag: json:"energy"
	Energy int32 `protobuf:"varint,2,opt,name=energy,proto3" json:"energy"` //能量消耗
	// @inject_tag: json:"study_ratio"
	StudyRatio int32 `protobuf:"varint,3,opt,name=study_ratio,json=studyRatio,proto3" json:"study_ratio"` //学习契约系数
	// @inject_tag: json:"load_ratio"
	LoadRatio int32 `protobuf:"varint,4,opt,name=load_ratio,json=loadRatio,proto3" json:"load_ratio"` //装载契约系数
	// @inject_tag: json:"study_properties"
	StudyProperties map[int32]int32 `protobuf:"bytes,5,rep,name=study_properties,json=studyProperties,proto3" json:"study_properties" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //学习属性加成
	// @inject_tag: json:"load_properties"
	LoadProperties map[int32]int32 `protobuf:"bytes,6,rep,name=load_properties,json=loadProperties,proto3" json:"load_properties" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //装载属性加成
	// @inject_tag: json:"skills"
	Skills []*SoulSkill `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills"` //子技能
}

func (x *GetsSoulRes) Reset() {
	*x = GetsSoulRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsSoulRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsSoulRes) ProtoMessage() {}

func (x *GetsSoulRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsSoulRes.ProtoReflect.Descriptor instead.
func (*GetsSoulRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetsSoulRes) GetCd() int32 {
	if x != nil {
		return x.Cd
	}
	return 0
}

func (x *GetsSoulRes) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *GetsSoulRes) GetStudyRatio() int32 {
	if x != nil {
		return x.StudyRatio
	}
	return 0
}

func (x *GetsSoulRes) GetLoadRatio() int32 {
	if x != nil {
		return x.LoadRatio
	}
	return 0
}

func (x *GetsSoulRes) GetStudyProperties() map[int32]int32 {
	if x != nil {
		return x.StudyProperties
	}
	return nil
}

func (x *GetsSoulRes) GetLoadProperties() map[int32]int32 {
	if x != nil {
		return x.LoadProperties
	}
	return nil
}

func (x *GetsSoulRes) GetSkills() []*SoulSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// //////////////////////////////////
type Discharge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"money"
	Money int32 `protobuf:"varint,2,opt,name=money,proto3" json:"money"` //所需金额
	// @inject_tag: json:"diamond"
	Diamond int32 `protobuf:"varint,3,opt,name=diamond,proto3" json:"diamond"` //基础砖石
	// @inject_tag: json:"present"
	Present int32 `protobuf:"varint,4,opt,name=present,proto3" json:"present"` //赠送砖石
	// @inject_tag: json:"first_present"
	FirstPresent int32 `protobuf:"varint,5,opt,name=first_present,json=firstPresent,proto3" json:"first_present"` //首充赠送砖石 0-表示首充不赠送
}

func (x *Discharge) Reset() {
	*x = Discharge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Discharge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discharge) ProtoMessage() {}

func (x *Discharge) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discharge.ProtoReflect.Descriptor instead.
func (*Discharge) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{12}
}

func (x *Discharge) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Discharge) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *Discharge) GetDiamond() int32 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *Discharge) GetPresent() int32 {
	if x != nil {
		return x.Present
	}
	return 0
}

func (x *Discharge) GetFirstPresent() int32 {
	if x != nil {
		return x.FirstPresent
	}
	return 0
}

type Commodity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"` //商品ID
	// @inject_tag: json:"shop_id"
	ShopId int32 `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id"` //商店ID(0-代表所有商店）
	// @inject_tag: json:"money_type"
	MoneyType int32 `protobuf:"varint,3,opt,name=money_type,json=moneyType,proto3" json:"money_type"` //货币类型 0-钻石，1-金币
	// @inject_tag: json:"price"
	Price int32 `protobuf:"varint,4,opt,name=price,proto3" json:"price"` //价格
	// @inject_tag: json:"goods_count"
	GoodsCount *GoodsCount `protobuf:"bytes,5,opt,name=goods_count,json=goodsCount,proto3" json:"goods_count"` //物品数量
}

func (x *Commodity) Reset() {
	*x = Commodity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commodity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commodity) ProtoMessage() {}

func (x *Commodity) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commodity.ProtoReflect.Descriptor instead.
func (*Commodity) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{13}
}

func (x *Commodity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Commodity) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *Commodity) GetMoneyType() int32 {
	if x != nil {
		return x.MoneyType
	}
	return 0
}

func (x *Commodity) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Commodity) GetGoodsCount() *GoodsCount {
	if x != nil {
		return x.GoodsCount
	}
	return nil
}

type Gift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"` //商品ID
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"` //名称
	// @inject_tag: json:"type"
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type"` //类型（0-日礼包，1-周礼包，2-月礼包）
	// @inject_tag: json:"shop_id"
	ShopId int32 `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id"` //商店ID(0-代表所有商店）
	// @inject_tag: json:"tag"
	Tag int32 `protobuf:"varint,5,opt,name=tag,proto3" json:"tag"` //标签（0-热卖，1-折扣等）
	// @inject_tag: json:"purchase_limit"
	PurchaseLimit int32 `protobuf:"varint,6,opt,name=purchase_limit,json=purchaseLimit,proto3" json:"purchase_limit"` //物品ID
	// @inject_tag: json:"money_type"
	MoneyType int32 `protobuf:"varint,7,opt,name=money_type,json=moneyType,proto3" json:"money_type"` //货币类型 0-钻石，1-金币
	// @inject_tag: json:"price"
	Price int32 `protobuf:"varint,8,opt,name=price,proto3" json:"price"` //价格
	// @inject_tag: json:"gift_goods"
	GiftGoods []*GoodsCount `protobuf:"bytes,9,rep,name=gift_goods,json=giftGoods,proto3" json:"gift_goods"` //礼包物品
}

func (x *Gift) Reset() {
	*x = Gift{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{14}
}

func (x *Gift) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Gift) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gift) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Gift) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *Gift) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Gift) GetPurchaseLimit() int32 {
	if x != nil {
		return x.PurchaseLimit
	}
	return 0
}

func (x *Gift) GetMoneyType() int32 {
	if x != nil {
		return x.MoneyType
	}
	return 0
}

func (x *Gift) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Gift) GetGiftGoods() []*GoodsCount {
	if x != nil {
		return x.GiftGoods
	}
	return nil
}

type BuildConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"` //物品ID
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"` //名称
	// @inject_tag: json:"level"
	Level int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level"` //等级
	// @inject_tag: json:"has_count"
	HasCount int32 `protobuf:"varint,4,opt,name=has_count,json=hasCount,proto3" json:"has_count"` //拥有数量
	// @inject_tag: json:"max_count"
	MaxCount int32 `protobuf:"varint,5,opt,name=max_count,json=maxCount,proto3" json:"max_count"` //最大数量
	// @inject_tag: json:"upgrade_time"
	UpgradeTime int32 `protobuf:"varint,6,opt,name=upgrade_time,json=upgradeTime,proto3" json:"upgrade_time"` //升级时长
	// @inject_tag: json:"upgrade_goods"
	UpgradeGoods []*GoodsCount `protobuf:"bytes,7,rep,name=upgrade_goods,json=upgradeGoods,proto3" json:"upgrade_goods"` //升级所需物品
}

func (x *BuildConf) Reset() {
	*x = BuildConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildConf) ProtoMessage() {}

func (x *BuildConf) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildConf.ProtoReflect.Descriptor instead.
func (*BuildConf) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{15}
}

func (x *BuildConf) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildConf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildConf) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BuildConf) GetHasCount() int32 {
	if x != nil {
		return x.HasCount
	}
	return 0
}

func (x *BuildConf) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *BuildConf) GetUpgradeTime() int32 {
	if x != nil {
		return x.UpgradeTime
	}
	return 0
}

func (x *BuildConf) GetUpgradeGoods() []*GoodsCount {
	if x != nil {
		return x.UpgradeGoods
	}
	return nil
}

type SoulSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"soul_id"
	SoulId int32 `protobuf:"varint,1,opt,name=soul_id,json=soulId,proto3" json:"soul_id"` //契约ID
	// @inject_tag: json:"skill_id"
	SkillId int32 `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id"` //技能ID
	// @inject_tag: json:"sub_index"
	SubIndex int32 `protobuf:"varint,3,opt,name=sub_index,json=subIndex,proto3" json:"sub_index"` //技能下标
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name"` // 技能名称
	// @inject_tag: json:"required"
	Required int32 `protobuf:"varint,5,opt,name=required,proto3" json:"required"` //触发条件
	// @inject_tag: json:"skill_type"
	SkillType int32 `protobuf:"varint,7,opt,name=skill_type,json=skillType,proto3" json:"skill_type"` //技能类型
	// @inject_tag: json:"target"
	Target int32 `protobuf:"varint,8,opt,name=target,proto3" json:"target"` //目标
	// @inject_tag: json:"value"
	Value int32 `protobuf:"varint,9,opt,name=value,proto3" json:"value"` //伤害或治疗值百分比（value + value*（level-1）/100）
	// @inject_tag: json:"desc"
	Desc string `protobuf:"bytes,10,opt,name=desc,proto3" json:"desc"` //技能描述
	// @inject_tag: json:"buff"
	Buff *SKillBuff `protobuf:"bytes,11,opt,name=buff,proto3" json:"buff"` //附加效果
}

func (x *SoulSkill) Reset() {
	*x = SoulSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoulSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoulSkill) ProtoMessage() {}

func (x *SoulSkill) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoulSkill.ProtoReflect.Descriptor instead.
func (*SoulSkill) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{16}
}

func (x *SoulSkill) GetSoulId() int32 {
	if x != nil {
		return x.SoulId
	}
	return 0
}

func (x *SoulSkill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SoulSkill) GetSubIndex() int32 {
	if x != nil {
		return x.SubIndex
	}
	return 0
}

func (x *SoulSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SoulSkill) GetRequired() int32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *SoulSkill) GetSkillType() int32 {
	if x != nil {
		return x.SkillType
	}
	return 0
}

func (x *SoulSkill) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *SoulSkill) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SoulSkill) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *SoulSkill) GetBuff() *SKillBuff {
	if x != nil {
		return x.Buff
	}
	return nil
}

type SKillBuff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"` //名称
	// @inject_tag: json:"self"
	Self int32 `protobuf:"varint,3,opt,name=self,proto3" json:"self"` //是否施加给自己
	// @inject_tag: json:"type"
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type"` //类型
	// @inject_tag: json:"effect"
	Effect int32 `protobuf:"varint,5,opt,name=effect,proto3" json:"effect"` //效果
	// @inject_tag: json:"can_add"
	CanAdd int32 `protobuf:"varint,6,opt,name=can_add,json=canAdd,proto3" json:"can_add"` //能否迭加
	// @inject_tag: json:"continued"
	Continued int32 `protobuf:"varint,7,opt,name=continued,proto3" json:"continued"` //持续回合
	// @inject_tag: json:"value"
	Value int32 `protobuf:"varint,8,opt,name=value,proto3" json:"value"` //增加或减少值
	// @inject_tag: json:"desc"
	Desc string `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc"` // 附加效果描述
}

func (x *SKillBuff) Reset() {
	*x = SKillBuff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_config_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKillBuff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKillBuff) ProtoMessage() {}

func (x *SKillBuff) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_config_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKillBuff.ProtoReflect.Descriptor instead.
func (*SKillBuff) Descriptor() ([]byte, []int) {
	return file_pb_proto_config_proto_rawDescGZIP(), []int{17}
}

func (x *SKillBuff) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SKillBuff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SKillBuff) GetSelf() int32 {
	if x != nil {
		return x.Self
	}
	return 0
}

func (x *SKillBuff) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SKillBuff) GetEffect() int32 {
	if x != nil {
		return x.Effect
	}
	return 0
}

func (x *SKillBuff) GetCanAdd() int32 {
	if x != nil {
		return x.CanAdd
	}
	return 0
}

func (x *SKillBuff) GetContinued() int32 {
	if x != nil {
		return x.Continued
	}
	return 0
}

func (x *SKillBuff) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SKillBuff) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_pb_proto_config_proto protoreflect.FileDescriptor

var file_pb_proto_config_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x15, 0x70, 0x62, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xca, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x41, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x69, 0x74, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f, 0x67, 0x69,
	0x66, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0a,
	0x67, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x13, 0x67, 0x65,
	0x74, 0x73, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x73, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52,
	0x10, 0x67, 0x65, 0x74, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65,
	0x71, 0x12, 0x35, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x73, 0x5f, 0x73, 0x6f, 0x75, 0x6c, 0x5f, 0x72,
	0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x73, 0x53, 0x6f, 0x75, 0x6c, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74,
	0x73, 0x53, 0x6f, 0x75, 0x6c, 0x52, 0x65, 0x71, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x22,
	0xca, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a,
	0x11, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x0f, 0x67, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x41, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74,
	0x79, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x48, 0x00, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f, 0x67, 0x69, 0x66, 0x74, 0x5f,
	0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74,
	0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x73, 0x5f,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x10, 0x67, 0x65,
	0x74, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x12, 0x35,
	0x0a, 0x0d, 0x67, 0x65, 0x74, 0x73, 0x5f, 0x73, 0x6f, 0x75, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x53,
	0x6f, 0x75, 0x6c, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x73, 0x53, 0x6f,
	0x75, 0x6c, 0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x22,
	0x6d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x54,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x68,
	0x6f, 0x70, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x73, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x26, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x73, 0x53, 0x6f, 0x75, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6f,
	0x75, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x6c, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x68, 0x61,
	0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x68, 0x61,
	0x72, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x69, 0x73, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x71, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x1e, 0x0a, 0x05, 0x67, 0x69, 0x66, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x52, 0x05, 0x67, 0x69, 0x66, 0x74, 0x73, 0x22,
	0x9f, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a,
	0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x52, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x22, 0xc2, 0x03, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x73, 0x53, 0x6f, 0x75, 0x6c, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x75,
	0x64, 0x79, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x73, 0x74, 0x75, 0x64, 0x79, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x4f, 0x0a, 0x10, 0x73, 0x74, 0x75,
	0x64, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x53, 0x6f, 0x75,
	0x6c, 0x52, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x73, 0x74, 0x75, 0x64, 0x79,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0f, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x53, 0x6f, 0x75,
	0x6c, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6f,
	0x75, 0x6c, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x1a,
	0x42, 0x0a, 0x14, 0x53, 0x74, 0x75, 0x64, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x41, 0x0a, 0x13, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8a, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69,
	0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x61,
	0x6d, 0x6f, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x2f, 0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xf4, 0x01, 0x0a, 0x04, 0x47, 0x69, 0x66, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x67, 0x69, 0x66, 0x74,
	0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x09, 0x67, 0x69,
	0x66, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0xd7, 0x01, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x68, 0x61, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0d,
	0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x0c, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x22, 0x90, 0x02, 0x0a, 0x09, 0x53, 0x6f, 0x75, 0x6c, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x6c, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x75, 0x62, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x75, 0x66, 0x66, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4b, 0x69, 0x6c, 0x6c, 0x42, 0x75, 0x66, 0x66, 0x52, 0x04,
	0x62, 0x75, 0x66, 0x66, 0x22, 0xd0, 0x01, 0x0a, 0x09, 0x53, 0x4b, 0x69, 0x6c, 0x6c, 0x42, 0x75,
	0x66, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x5f, 0x61, 0x64,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x41, 0x64, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x62, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_config_proto_rawDescOnce sync.Once
	file_pb_proto_config_proto_rawDescData = file_pb_proto_config_proto_rawDesc
)

func file_pb_proto_config_proto_rawDescGZIP() []byte {
	file_pb_proto_config_proto_rawDescOnce.Do(func() {
		file_pb_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_config_proto_rawDescData)
	})
	return file_pb_proto_config_proto_rawDescData
}

var file_pb_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pb_proto_config_proto_goTypes = []interface{}{
	(*ConfigReq)(nil),        // 0: pb.ConfigReq
	(*ConfigRes)(nil),        // 1: pb.ConfigRes
	(*GetDischargeReq)(nil),  // 2: pb.GetDischargeReq
	(*GetCommodityReq)(nil),  // 3: pb.GetCommodityReq
	(*GetGiftReq)(nil),       // 4: pb.GetGiftReq
	(*GetsBuildConfReq)(nil), // 5: pb.GetsBuildConfReq
	(*GetsSoulReq)(nil),      // 6: pb.GetsSoulReq
	(*GetDischargeRes)(nil),  // 7: pb.GetDischargeRes
	(*GetCommodityRes)(nil),  // 8: pb.GetCommodityRes
	(*GetGiftRes)(nil),       // 9: pb.GetGiftRes
	(*GetsBuildConfRes)(nil), // 10: pb.GetsBuildConfRes
	(*GetsSoulRes)(nil),      // 11: pb.GetsSoulRes
	(*Discharge)(nil),        // 12: pb.Discharge
	(*Commodity)(nil),        // 13: pb.Commodity
	(*Gift)(nil),             // 14: pb.Gift
	(*BuildConf)(nil),        // 15: pb.BuildConf
	(*SoulSkill)(nil),        // 16: pb.SoulSkill
	(*SKillBuff)(nil),        // 17: pb.SKillBuff
	nil,                      // 18: pb.GetsSoulRes.StudyPropertiesEntry
	nil,                      // 19: pb.GetsSoulRes.LoadPropertiesEntry
	(*GoodsCount)(nil),       // 20: pb.GoodsCount
}
var file_pb_proto_config_proto_depIdxs = []int32{
	2,  // 0: pb.ConfigReq.get_discharge_req:type_name -> pb.GetDischargeReq
	3,  // 1: pb.ConfigReq.get_commodity_req:type_name -> pb.GetCommodityReq
	4,  // 2: pb.ConfigReq.get_gift_req:type_name -> pb.GetGiftReq
	5,  // 3: pb.ConfigReq.gets_build_conf_req:type_name -> pb.GetsBuildConfReq
	6,  // 4: pb.ConfigReq.gets_soul_req:type_name -> pb.GetsSoulReq
	7,  // 5: pb.ConfigRes.get_discharge_res:type_name -> pb.GetDischargeRes
	8,  // 6: pb.ConfigRes.get_commodity_res:type_name -> pb.GetCommodityRes
	9,  // 7: pb.ConfigRes.get_gift_res:type_name -> pb.GetGiftRes
	10, // 8: pb.ConfigRes.gets_build_conf_res:type_name -> pb.GetsBuildConfRes
	11, // 9: pb.ConfigRes.gets_soul_res:type_name -> pb.GetsSoulRes
	12, // 10: pb.GetDischargeRes.discharges:type_name -> pb.Discharge
	13, // 11: pb.GetCommodityRes.commodities:type_name -> pb.Commodity
	14, // 12: pb.GetGiftRes.gifts:type_name -> pb.Gift
	15, // 13: pb.GetsBuildConfRes.build_configs:type_name -> pb.BuildConf
	18, // 14: pb.GetsSoulRes.study_properties:type_name -> pb.GetsSoulRes.StudyPropertiesEntry
	19, // 15: pb.GetsSoulRes.load_properties:type_name -> pb.GetsSoulRes.LoadPropertiesEntry
	16, // 16: pb.GetsSoulRes.skills:type_name -> pb.SoulSkill
	20, // 17: pb.Commodity.goods_count:type_name -> pb.GoodsCount
	20, // 18: pb.Gift.gift_goods:type_name -> pb.GoodsCount
	20, // 19: pb.BuildConf.upgrade_goods:type_name -> pb.GoodsCount
	17, // 20: pb.SoulSkill.buff:type_name -> pb.SKillBuff
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pb_proto_config_proto_init() }
func file_pb_proto_config_proto_init() {
	if File_pb_proto_config_proto != nil {
		return
	}
	file_pb_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDischargeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommodityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGiftReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsBuildConfReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsSoulReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDischargeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommodityRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGiftRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsBuildConfRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsSoulRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Discharge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commodity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoulSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_config_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKillBuff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_proto_config_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ConfigReq_GetDischargeReq)(nil),
		(*ConfigReq_GetCommodityReq)(nil),
		(*ConfigReq_GetGiftReq)(nil),
		(*ConfigReq_GetsBuildConfReq)(nil),
		(*ConfigReq_GetsSoulReq)(nil),
	}
	file_pb_proto_config_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ConfigRes_GetDischargeRes)(nil),
		(*ConfigRes_GetCommodityRes)(nil),
		(*ConfigRes_GetGiftRes)(nil),
		(*ConfigRes_GetsBuildConfRes)(nil),
		(*ConfigRes_GetsSoulRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_proto_config_proto_goTypes,
		DependencyIndexes: file_pb_proto_config_proto_depIdxs,
		MessageInfos:      file_pb_proto_config_proto_msgTypes,
	}.Build()
	File_pb_proto_config_proto = out.File
	file_pb_proto_config_proto_rawDesc = nil
	file_pb_proto_config_proto_goTypes = nil
	file_pb_proto_config_proto_depIdxs = nil
}
