// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: pb/proto/family.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlantStage int32

const (
	PlantStage_zero  PlantStage = 0
	PlantStage_One   PlantStage = 1
	PlantStage_Two   PlantStage = 2
	PlantStage_Three PlantStage = 3
)

// Enum value maps for PlantStage.
var (
	PlantStage_name = map[int32]string{
		0: "zero",
		1: "One",
		2: "Two",
		3: "Three",
	}
	PlantStage_value = map[string]int32{
		"zero":  0,
		"One":   1,
		"Two":   2,
		"Three": 3,
	}
)

func (x PlantStage) Enum() *PlantStage {
	p := new(PlantStage)
	*p = x
	return p
}

func (x PlantStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlantStage) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[0].Descriptor()
}

func (PlantStage) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[0]
}

func (x PlantStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlantStage.Descriptor instead.
func (PlantStage) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{0}
}

type PlantOperate int32

const (
	PlantOperate_None    PlantOperate = 0 //无操作
	PlantOperate_Harvest PlantOperate = 1 //收割（庄稼）
)

// Enum value maps for PlantOperate.
var (
	PlantOperate_name = map[int32]string{
		0: "None",
		1: "Harvest",
	}
	PlantOperate_value = map[string]int32{
		"None":    0,
		"Harvest": 1,
	}
)

func (x PlantOperate) Enum() *PlantOperate {
	p := new(PlantOperate)
	*p = x
	return p
}

func (x PlantOperate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlantOperate) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[1].Descriptor()
}

func (PlantOperate) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[1]
}

func (x PlantOperate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlantOperate.Descriptor instead.
func (PlantOperate) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{1}
}

type CreateBuildRes_Result int32

const (
	CreateBuildRes_Success     CreateBuildRes_Result = 0 //建筑成功
	CreateBuildRes_NoBuildConf CreateBuildRes_Result = 1 //建筑设施不存在
	CreateBuildRes_BuildLimit  CreateBuildRes_Result = 2 //超出建筑最大数量
	CreateBuildRes_HasBuild    CreateBuildRes_Result = 3 //位置上已存在建筑
	CreateBuildRes_GoodsError  CreateBuildRes_Result = 4 //所需资源不足
	CreateBuildRes_MysqlError  CreateBuildRes_Result = 5 //数据库异常
)

// Enum value maps for CreateBuildRes_Result.
var (
	CreateBuildRes_Result_name = map[int32]string{
		0: "Success",
		1: "NoBuildConf",
		2: "BuildLimit",
		3: "HasBuild",
		4: "GoodsError",
		5: "MysqlError",
	}
	CreateBuildRes_Result_value = map[string]int32{
		"Success":     0,
		"NoBuildConf": 1,
		"BuildLimit":  2,
		"HasBuild":    3,
		"GoodsError":  4,
		"MysqlError":  5,
	}
)

func (x CreateBuildRes_Result) Enum() *CreateBuildRes_Result {
	p := new(CreateBuildRes_Result)
	*p = x
	return p
}

func (x CreateBuildRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateBuildRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[2].Descriptor()
}

func (CreateBuildRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[2]
}

func (x CreateBuildRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateBuildRes_Result.Descriptor instead.
func (CreateBuildRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{12, 0}
}

type CancelBuildRes_Result int32

const (
	CancelBuildRes_Success     CancelBuildRes_Result = 0 //取消建筑成功
	CancelBuildRes_MysqlError  CancelBuildRes_Result = 1 //数据库异常
	CancelBuildRes_NotExist    CancelBuildRes_Result = 2 //建筑不存在
	CancelBuildRes_NoBuildConf CancelBuildRes_Result = 3 //建筑设施不存在
	CancelBuildRes_BuildFinish CancelBuildRes_Result = 4 //建造已完成
)

// Enum value maps for CancelBuildRes_Result.
var (
	CancelBuildRes_Result_name = map[int32]string{
		0: "Success",
		1: "MysqlError",
		2: "NotExist",
		3: "NoBuildConf",
		4: "BuildFinish",
	}
	CancelBuildRes_Result_value = map[string]int32{
		"Success":     0,
		"MysqlError":  1,
		"NotExist":    2,
		"NoBuildConf": 3,
		"BuildFinish": 4,
	}
)

func (x CancelBuildRes_Result) Enum() *CancelBuildRes_Result {
	p := new(CancelBuildRes_Result)
	*p = x
	return p
}

func (x CancelBuildRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelBuildRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[3].Descriptor()
}

func (CancelBuildRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[3]
}

func (x CancelBuildRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelBuildRes_Result.Descriptor instead.
func (CancelBuildRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{13, 0}
}

type DeleteBuildRes_Result int32

const (
	DeleteBuildRes_Success    DeleteBuildRes_Result = 0 //取消建筑成功
	DeleteBuildRes_MysqlError DeleteBuildRes_Result = 1 //数据库异常
	DeleteBuildRes_NotExist   DeleteBuildRes_Result = 2 //建筑不存在
	DeleteBuildRes_Building   DeleteBuildRes_Result = 3 //建造中
)

// Enum value maps for DeleteBuildRes_Result.
var (
	DeleteBuildRes_Result_name = map[int32]string{
		0: "Success",
		1: "MysqlError",
		2: "NotExist",
		3: "Building",
	}
	DeleteBuildRes_Result_value = map[string]int32{
		"Success":    0,
		"MysqlError": 1,
		"NotExist":   2,
		"Building":   3,
	}
)

func (x DeleteBuildRes_Result) Enum() *DeleteBuildRes_Result {
	p := new(DeleteBuildRes_Result)
	*p = x
	return p
}

func (x DeleteBuildRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteBuildRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[4].Descriptor()
}

func (DeleteBuildRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[4]
}

func (x DeleteBuildRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteBuildRes_Result.Descriptor instead.
func (DeleteBuildRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{14, 0}
}

type PlantSeedRes_Result int32

const (
	PlantSeedRes_Success        PlantSeedRes_Result = 0
	PlantSeedRes_NoBuild        PlantSeedRes_Result = 1 //建筑不存在
	PlantSeedRes_BuildStatusErr PlantSeedRes_Result = 2 //建筑物状态不对
	PlantSeedRes_BuildConfErr   PlantSeedRes_Result = 3 //建筑设施不对
	PlantSeedRes_PlayerSeedErr  PlantSeedRes_Result = 4 //玩家种子不够
	PlantSeedRes_PlantStageErr  PlantSeedRes_Result = 5 //成长阶段错误
	PlantSeedRes_MysqlError     PlantSeedRes_Result = 6 //数据库异常
)

// Enum value maps for PlantSeedRes_Result.
var (
	PlantSeedRes_Result_name = map[int32]string{
		0: "Success",
		1: "NoBuild",
		2: "BuildStatusErr",
		3: "BuildConfErr",
		4: "PlayerSeedErr",
		5: "PlantStageErr",
		6: "MysqlError",
	}
	PlantSeedRes_Result_value = map[string]int32{
		"Success":        0,
		"NoBuild":        1,
		"BuildStatusErr": 2,
		"BuildConfErr":   3,
		"PlayerSeedErr":  4,
		"PlantStageErr":  5,
		"MysqlError":     6,
	}
)

func (x PlantSeedRes_Result) Enum() *PlantSeedRes_Result {
	p := new(PlantSeedRes_Result)
	*p = x
	return p
}

func (x PlantSeedRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlantSeedRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[5].Descriptor()
}

func (PlantSeedRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[5]
}

func (x PlantSeedRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlantSeedRes_Result.Descriptor instead.
func (PlantSeedRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{16, 0}
}

type HarvestRes_Result int32

const (
	HarvestRes_Success    HarvestRes_Result = 0
	HarvestRes_MysqlError HarvestRes_Result = 1 //数据库异常
	HarvestRes_NoBuild    HarvestRes_Result = 2 //建筑不存在
	HarvestRes_NoPlanting HarvestRes_Result = 3 //建筑物上未种植
)

// Enum value maps for HarvestRes_Result.
var (
	HarvestRes_Result_name = map[int32]string{
		0: "Success",
		1: "MysqlError",
		2: "NoBuild",
		3: "NoPlanting",
	}
	HarvestRes_Result_value = map[string]int32{
		"Success":    0,
		"MysqlError": 1,
		"NoBuild":    2,
		"NoPlanting": 3,
	}
)

func (x HarvestRes_Result) Enum() *HarvestRes_Result {
	p := new(HarvestRes_Result)
	*p = x
	return p
}

func (x HarvestRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HarvestRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[6].Descriptor()
}

func (HarvestRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[6]
}

func (x HarvestRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HarvestRes_Result.Descriptor instead.
func (HarvestRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{17, 0}
}

type BuildStateNotify_Result int32

const (
	BuildStateNotify_Success     BuildStateNotify_Result = 0 //建筑成功
	BuildStateNotify_NoBuildConf BuildStateNotify_Result = 1 //建筑设施不存在
	BuildStateNotify_BuildLimit  BuildStateNotify_Result = 2 //超出建筑最大数量
	BuildStateNotify_HasBuild    BuildStateNotify_Result = 3 //位置上已存在建筑
	BuildStateNotify_GoodsError  BuildStateNotify_Result = 4 //所需资源不足
	BuildStateNotify_MysqlError  BuildStateNotify_Result = 5 //数据库异常
)

// Enum value maps for BuildStateNotify_Result.
var (
	BuildStateNotify_Result_name = map[int32]string{
		0: "Success",
		1: "NoBuildConf",
		2: "BuildLimit",
		3: "HasBuild",
		4: "GoodsError",
		5: "MysqlError",
	}
	BuildStateNotify_Result_value = map[string]int32{
		"Success":     0,
		"NoBuildConf": 1,
		"BuildLimit":  2,
		"HasBuild":    3,
		"GoodsError":  4,
		"MysqlError":  5,
	}
)

func (x BuildStateNotify_Result) Enum() *BuildStateNotify_Result {
	p := new(BuildStateNotify_Result)
	*p = x
	return p
}

func (x BuildStateNotify_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStateNotify_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[7].Descriptor()
}

func (BuildStateNotify_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[7]
}

func (x BuildStateNotify_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStateNotify_Result.Descriptor instead.
func (BuildStateNotify_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{18, 0}
}

type PlayerBuild_Status int32

const (
	PlayerBuild_Normal   PlayerBuild_Status = 0 //空闲中
	PlayerBuild_Building PlayerBuild_Status = 1 //建造中
	PlayerBuild_Planting PlayerBuild_Status = 2 //种植中
)

// Enum value maps for PlayerBuild_Status.
var (
	PlayerBuild_Status_name = map[int32]string{
		0: "Normal",
		1: "Building",
		2: "Planting",
	}
	PlayerBuild_Status_value = map[string]int32{
		"Normal":   0,
		"Building": 1,
		"Planting": 2,
	}
)

func (x PlayerBuild_Status) Enum() *PlayerBuild_Status {
	p := new(PlayerBuild_Status)
	*p = x
	return p
}

func (x PlayerBuild_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerBuild_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_family_proto_enumTypes[8].Descriptor()
}

func (PlayerBuild_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_family_proto_enumTypes[8]
}

func (x PlayerBuild_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerBuild_Status.Descriptor instead.
func (PlayerBuild_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{19, 0}
}

type FamilyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//
	//	*FamilyReq_EnterFamilyReq
	//	*FamilyReq_ExitFamilyReq
	//	*FamilyReq_CreateBuildReq
	//	*FamilyReq_CancelBuildReq
	//	*FamilyReq_DeleteBuildReq
	//	*FamilyReq_GetsSeedReq
	//	*FamilyReq_PlantSeedReq
	//	*FamilyReq_HarvestReq
	Req isFamilyReq_Req `protobuf_oneof:"req"`
}

func (x *FamilyReq) Reset() {
	*x = FamilyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyReq) ProtoMessage() {}

func (x *FamilyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyReq.ProtoReflect.Descriptor instead.
func (*FamilyReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{0}
}

func (m *FamilyReq) GetReq() isFamilyReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *FamilyReq) GetEnterFamilyReq() *EnterFamilyReq {
	if x, ok := x.GetReq().(*FamilyReq_EnterFamilyReq); ok {
		return x.EnterFamilyReq
	}
	return nil
}

func (x *FamilyReq) GetExitFamilyReq() *ExitFamilyReq {
	if x, ok := x.GetReq().(*FamilyReq_ExitFamilyReq); ok {
		return x.ExitFamilyReq
	}
	return nil
}

func (x *FamilyReq) GetCreateBuildReq() *CreateBuildReq {
	if x, ok := x.GetReq().(*FamilyReq_CreateBuildReq); ok {
		return x.CreateBuildReq
	}
	return nil
}

func (x *FamilyReq) GetCancelBuildReq() *CancelBuildReq {
	if x, ok := x.GetReq().(*FamilyReq_CancelBuildReq); ok {
		return x.CancelBuildReq
	}
	return nil
}

func (x *FamilyReq) GetDeleteBuildReq() *DeleteBuildReq {
	if x, ok := x.GetReq().(*FamilyReq_DeleteBuildReq); ok {
		return x.DeleteBuildReq
	}
	return nil
}

func (x *FamilyReq) GetGetsSeedReq() *GetsSeedReq {
	if x, ok := x.GetReq().(*FamilyReq_GetsSeedReq); ok {
		return x.GetsSeedReq
	}
	return nil
}

func (x *FamilyReq) GetPlantSeedReq() *PlantSeedReq {
	if x, ok := x.GetReq().(*FamilyReq_PlantSeedReq); ok {
		return x.PlantSeedReq
	}
	return nil
}

func (x *FamilyReq) GetHarvestReq() *HarvestReq {
	if x, ok := x.GetReq().(*FamilyReq_HarvestReq); ok {
		return x.HarvestReq
	}
	return nil
}

type isFamilyReq_Req interface {
	isFamilyReq_Req()
}

type FamilyReq_EnterFamilyReq struct {
	EnterFamilyReq *EnterFamilyReq `protobuf:"bytes,1,opt,name=enter_family_req,json=enterFamilyReq,proto3,oneof"` //进入家族
}

type FamilyReq_ExitFamilyReq struct {
	ExitFamilyReq *ExitFamilyReq `protobuf:"bytes,2,opt,name=exit_family_req,json=exitFamilyReq,proto3,oneof"` //离开家族
}

type FamilyReq_CreateBuildReq struct {
	CreateBuildReq *CreateBuildReq `protobuf:"bytes,3,opt,name=create_build_req,json=createBuildReq,proto3,oneof"` //创建建筑
}

type FamilyReq_CancelBuildReq struct {
	CancelBuildReq *CancelBuildReq `protobuf:"bytes,4,opt,name=cancel_build_req,json=cancelBuildReq,proto3,oneof"` //取消建设中的建筑
}

type FamilyReq_DeleteBuildReq struct {
	DeleteBuildReq *DeleteBuildReq `protobuf:"bytes,5,opt,name=delete_build_req,json=deleteBuildReq,proto3,oneof"` //拆除建筑
}

type FamilyReq_GetsSeedReq struct {
	GetsSeedReq *GetsSeedReq `protobuf:"bytes,6,opt,name=gets_seed_req,json=getsSeedReq,proto3,oneof"` //获取可以种植的种子
}

type FamilyReq_PlantSeedReq struct {
	PlantSeedReq *PlantSeedReq `protobuf:"bytes,7,opt,name=plant_seed_req,json=plantSeedReq,proto3,oneof"` //种植
}

type FamilyReq_HarvestReq struct {
	HarvestReq *HarvestReq `protobuf:"bytes,8,opt,name=harvest_req,json=harvestReq,proto3,oneof"` //收割庄稼
}

func (*FamilyReq_EnterFamilyReq) isFamilyReq_Req() {}

func (*FamilyReq_ExitFamilyReq) isFamilyReq_Req() {}

func (*FamilyReq_CreateBuildReq) isFamilyReq_Req() {}

func (*FamilyReq_CancelBuildReq) isFamilyReq_Req() {}

func (*FamilyReq_DeleteBuildReq) isFamilyReq_Req() {}

func (*FamilyReq_GetsSeedReq) isFamilyReq_Req() {}

func (*FamilyReq_PlantSeedReq) isFamilyReq_Req() {}

func (*FamilyReq_HarvestReq) isFamilyReq_Req() {}

type FamilyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//
	//	*FamilyRes_EnterFamilyRes
	//	*FamilyRes_ExitFamilyRes
	//	*FamilyRes_CreateBuildRes
	//	*FamilyRes_CancelBuildRes
	//	*FamilyRes_DeleteBuildRes
	//	*FamilyRes_GetsSeedRes
	//	*FamilyRes_PlantSeedRes
	//	*FamilyRes_HarvestRes
	//	*FamilyRes_BuildStateNotify
	Res isFamilyRes_Res `protobuf_oneof:"res"`
}

func (x *FamilyRes) Reset() {
	*x = FamilyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyRes) ProtoMessage() {}

func (x *FamilyRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyRes.ProtoReflect.Descriptor instead.
func (*FamilyRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{1}
}

func (m *FamilyRes) GetRes() isFamilyRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *FamilyRes) GetEnterFamilyRes() *EnterFamilyRes {
	if x, ok := x.GetRes().(*FamilyRes_EnterFamilyRes); ok {
		return x.EnterFamilyRes
	}
	return nil
}

func (x *FamilyRes) GetExitFamilyRes() *ExitFamilyRes {
	if x, ok := x.GetRes().(*FamilyRes_ExitFamilyRes); ok {
		return x.ExitFamilyRes
	}
	return nil
}

func (x *FamilyRes) GetCreateBuildRes() *CreateBuildRes {
	if x, ok := x.GetRes().(*FamilyRes_CreateBuildRes); ok {
		return x.CreateBuildRes
	}
	return nil
}

func (x *FamilyRes) GetCancelBuildRes() *CancelBuildRes {
	if x, ok := x.GetRes().(*FamilyRes_CancelBuildRes); ok {
		return x.CancelBuildRes
	}
	return nil
}

func (x *FamilyRes) GetDeleteBuildRes() *DeleteBuildRes {
	if x, ok := x.GetRes().(*FamilyRes_DeleteBuildRes); ok {
		return x.DeleteBuildRes
	}
	return nil
}

func (x *FamilyRes) GetGetsSeedRes() *GetsSeedRes {
	if x, ok := x.GetRes().(*FamilyRes_GetsSeedRes); ok {
		return x.GetsSeedRes
	}
	return nil
}

func (x *FamilyRes) GetPlantSeedRes() *PlantSeedRes {
	if x, ok := x.GetRes().(*FamilyRes_PlantSeedRes); ok {
		return x.PlantSeedRes
	}
	return nil
}

func (x *FamilyRes) GetHarvestRes() *HarvestRes {
	if x, ok := x.GetRes().(*FamilyRes_HarvestRes); ok {
		return x.HarvestRes
	}
	return nil
}

func (x *FamilyRes) GetBuildStateNotify() *BuildStateNotify {
	if x, ok := x.GetRes().(*FamilyRes_BuildStateNotify); ok {
		return x.BuildStateNotify
	}
	return nil
}

type isFamilyRes_Res interface {
	isFamilyRes_Res()
}

type FamilyRes_EnterFamilyRes struct {
	EnterFamilyRes *EnterFamilyRes `protobuf:"bytes,1,opt,name=enter_family_res,json=enterFamilyRes,proto3,oneof"` //进入家族
}

type FamilyRes_ExitFamilyRes struct {
	ExitFamilyRes *ExitFamilyRes `protobuf:"bytes,2,opt,name=exit_family_res,json=exitFamilyRes,proto3,oneof"` //离开家族
}

type FamilyRes_CreateBuildRes struct {
	CreateBuildRes *CreateBuildRes `protobuf:"bytes,3,opt,name=create_build_res,json=createBuildRes,proto3,oneof"` //创建建筑
}

type FamilyRes_CancelBuildRes struct {
	CancelBuildRes *CancelBuildRes `protobuf:"bytes,4,opt,name=cancel_build_res,json=cancelBuildRes,proto3,oneof"` //取消建设中的建筑
}

type FamilyRes_DeleteBuildRes struct {
	DeleteBuildRes *DeleteBuildRes `protobuf:"bytes,5,opt,name=delete_build_res,json=deleteBuildRes,proto3,oneof"` //拆除建筑
}

type FamilyRes_GetsSeedRes struct {
	GetsSeedRes *GetsSeedRes `protobuf:"bytes,6,opt,name=gets_seed_res,json=getsSeedRes,proto3,oneof"` //获取可以种植的种子
}

type FamilyRes_PlantSeedRes struct {
	PlantSeedRes *PlantSeedRes `protobuf:"bytes,7,opt,name=plant_seed_res,json=plantSeedRes,proto3,oneof"` //种植
}

type FamilyRes_HarvestRes struct {
	HarvestRes *HarvestRes `protobuf:"bytes,8,opt,name=harvest_res,json=harvestRes,proto3,oneof"` //收割庄稼
}

type FamilyRes_BuildStateNotify struct {
	BuildStateNotify *BuildStateNotify `protobuf:"bytes,100,opt,name=build_state_notify,json=buildStateNotify,proto3,oneof"` //建筑状态变化
}

func (*FamilyRes_EnterFamilyRes) isFamilyRes_Res() {}

func (*FamilyRes_ExitFamilyRes) isFamilyRes_Res() {}

func (*FamilyRes_CreateBuildRes) isFamilyRes_Res() {}

func (*FamilyRes_CancelBuildRes) isFamilyRes_Res() {}

func (*FamilyRes_DeleteBuildRes) isFamilyRes_Res() {}

func (*FamilyRes_GetsSeedRes) isFamilyRes_Res() {}

func (*FamilyRes_PlantSeedRes) isFamilyRes_Res() {}

func (*FamilyRes_HarvestRes) isFamilyRes_Res() {}

func (*FamilyRes_BuildStateNotify) isFamilyRes_Res() {}

// //////////////////////////////////////////
type EnterFamilyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnterFamilyReq) Reset() {
	*x = EnterFamilyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterFamilyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterFamilyReq) ProtoMessage() {}

func (x *EnterFamilyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterFamilyReq.ProtoReflect.Descriptor instead.
func (*EnterFamilyReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{2}
}

type ExitFamilyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExitFamilyReq) Reset() {
	*x = ExitFamilyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitFamilyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitFamilyReq) ProtoMessage() {}

func (x *ExitFamilyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitFamilyReq.ProtoReflect.Descriptor instead.
func (*ExitFamilyReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{3}
}

type CreateBuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"build_conf_id"
	BuildConfId int32 `protobuf:"varint,1,opt,name=build_conf_id,json=buildConfId,proto3" json:"build_conf_id"`
	// @inject_tag: json:"level"
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level"`
	// @inject_tag: json:"poses"
	Poses []int32 `protobuf:"varint,3,rep,packed,name=poses,proto3" json:"poses"`
}

func (x *CreateBuildReq) Reset() {
	*x = CreateBuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildReq) ProtoMessage() {}

func (x *CreateBuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildReq.ProtoReflect.Descriptor instead.
func (*CreateBuildReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBuildReq) GetBuildConfId() int32 {
	if x != nil {
		return x.BuildConfId
	}
	return 0
}

func (x *CreateBuildReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateBuildReq) GetPoses() []int32 {
	if x != nil {
		return x.Poses
	}
	return nil
}

type CancelBuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
}

func (x *CancelBuildReq) Reset() {
	*x = CancelBuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildReq) ProtoMessage() {}

func (x *CancelBuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildReq.ProtoReflect.Descriptor instead.
func (*CancelBuildReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{5}
}

func (x *CancelBuildReq) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

type DeleteBuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
}

func (x *DeleteBuildReq) Reset() {
	*x = DeleteBuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildReq) ProtoMessage() {}

func (x *DeleteBuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildReq.ProtoReflect.Descriptor instead.
func (*DeleteBuildReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBuildReq) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

type GetsSeedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
}

func (x *GetsSeedReq) Reset() {
	*x = GetsSeedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsSeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsSeedReq) ProtoMessage() {}

func (x *GetsSeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsSeedReq.ProtoReflect.Descriptor instead.
func (*GetsSeedReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{7}
}

func (x *GetsSeedReq) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

type PlantSeedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
	// @inject_tag: json:"goods_id"
	GoodsId int32 `protobuf:"varint,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id"` //种子Id
}

func (x *PlantSeedReq) Reset() {
	*x = PlantSeedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantSeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantSeedReq) ProtoMessage() {}

func (x *PlantSeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantSeedReq.ProtoReflect.Descriptor instead.
func (*PlantSeedReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{8}
}

func (x *PlantSeedReq) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

func (x *PlantSeedReq) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type HarvestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
}

func (x *HarvestReq) Reset() {
	*x = HarvestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HarvestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestReq) ProtoMessage() {}

func (x *HarvestReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestReq.ProtoReflect.Descriptor instead.
func (*HarvestReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{9}
}

func (x *HarvestReq) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

// //////////////////////////////////////////
type EnterFamilyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"server_time"
	ServerTime int64 `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time"`
	// @inject_tag: json:"builds"
	Builds []*PlayerBuild `protobuf:"bytes,2,rep,name=builds,proto3" json:"builds"`
}

func (x *EnterFamilyRes) Reset() {
	*x = EnterFamilyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterFamilyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterFamilyRes) ProtoMessage() {}

func (x *EnterFamilyRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterFamilyRes.ProtoReflect.Descriptor instead.
func (*EnterFamilyRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{10}
}

func (x *EnterFamilyRes) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *EnterFamilyRes) GetBuilds() []*PlayerBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

type ExitFamilyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExitFamilyRes) Reset() {
	*x = ExitFamilyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitFamilyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitFamilyRes) ProtoMessage() {}

func (x *ExitFamilyRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitFamilyRes.ProtoReflect.Descriptor instead.
func (*ExitFamilyRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{11}
}

type CreateBuildRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result CreateBuildRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.CreateBuildRes_Result" json:"result"`
	// @inject_tag: json:"build"
	Build *PlayerBuild `protobuf:"bytes,2,opt,name=build,proto3" json:"build"`
	// @inject_tag: json:"upgrade_goods"
	UpgradeGoods []*GoodsCount `protobuf:"bytes,3,rep,name=upgrade_goods,json=upgradeGoods,proto3" json:"upgrade_goods"` //升级所需资源
}

func (x *CreateBuildRes) Reset() {
	*x = CreateBuildRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBuildRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildRes) ProtoMessage() {}

func (x *CreateBuildRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildRes.ProtoReflect.Descriptor instead.
func (*CreateBuildRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBuildRes) GetResult() CreateBuildRes_Result {
	if x != nil {
		return x.Result
	}
	return CreateBuildRes_Success
}

func (x *CreateBuildRes) GetBuild() *PlayerBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *CreateBuildRes) GetUpgradeGoods() []*GoodsCount {
	if x != nil {
		return x.UpgradeGoods
	}
	return nil
}

type CancelBuildRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result CancelBuildRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.CancelBuildRes_Result" json:"result"`
	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,2,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
	// @inject_tag: json:"upgrade_goods"
	UpgradeGoods []*GoodsCount `protobuf:"bytes,3,rep,name=upgrade_goods,json=upgradeGoods,proto3" json:"upgrade_goods"` //返回升级所需资源
}

func (x *CancelBuildRes) Reset() {
	*x = CancelBuildRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBuildRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildRes) ProtoMessage() {}

func (x *CancelBuildRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildRes.ProtoReflect.Descriptor instead.
func (*CancelBuildRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{13}
}

func (x *CancelBuildRes) GetResult() CancelBuildRes_Result {
	if x != nil {
		return x.Result
	}
	return CancelBuildRes_Success
}

func (x *CancelBuildRes) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

func (x *CancelBuildRes) GetUpgradeGoods() []*GoodsCount {
	if x != nil {
		return x.UpgradeGoods
	}
	return nil
}

type DeleteBuildRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result DeleteBuildRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.DeleteBuildRes_Result" json:"result"`
	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,2,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
}

func (x *DeleteBuildRes) Reset() {
	*x = DeleteBuildRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBuildRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildRes) ProtoMessage() {}

func (x *DeleteBuildRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildRes.ProtoReflect.Descriptor instead.
func (*DeleteBuildRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBuildRes) GetResult() DeleteBuildRes_Result {
	if x != nil {
		return x.Result
	}
	return DeleteBuildRes_Success
}

func (x *DeleteBuildRes) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

type GetsSeedRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"build_id"
	BuildId int32 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id"` //建筑Id
	// @inject_tag: json:"seeds"
	Seeds []*Seed `protobuf:"bytes,2,rep,name=seeds,proto3" json:"seeds"` //种子数量
}

func (x *GetsSeedRes) Reset() {
	*x = GetsSeedRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsSeedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsSeedRes) ProtoMessage() {}

func (x *GetsSeedRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsSeedRes.ProtoReflect.Descriptor instead.
func (*GetsSeedRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{15}
}

func (x *GetsSeedRes) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

func (x *GetsSeedRes) GetSeeds() []*Seed {
	if x != nil {
		return x.Seeds
	}
	return nil
}

type PlantSeedRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result PlantSeedRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.PlantSeedRes_Result" json:"result"`
	// @inject_tag: json:"build"
	Build *PlayerBuild `protobuf:"bytes,2,opt,name=build,proto3" json:"build"`
}

func (x *PlantSeedRes) Reset() {
	*x = PlantSeedRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantSeedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantSeedRes) ProtoMessage() {}

func (x *PlantSeedRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantSeedRes.ProtoReflect.Descriptor instead.
func (*PlantSeedRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{16}
}

func (x *PlantSeedRes) GetResult() PlantSeedRes_Result {
	if x != nil {
		return x.Result
	}
	return PlantSeedRes_Success
}

func (x *PlantSeedRes) GetBuild() *PlayerBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

type HarvestRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result HarvestRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.HarvestRes_Result" json:"result"`
	// @inject_tag: json:"build"
	Build *PlayerBuild `protobuf:"bytes,2,opt,name=build,proto3" json:"build"`
	// @inject_tag: json:"goods_count"
	GoodsCount *GoodsCount `protobuf:"bytes,3,opt,name=goods_count,json=goodsCount,proto3" json:"goods_count"` //增加的农作物
}

func (x *HarvestRes) Reset() {
	*x = HarvestRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HarvestRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestRes) ProtoMessage() {}

func (x *HarvestRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestRes.ProtoReflect.Descriptor instead.
func (*HarvestRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{17}
}

func (x *HarvestRes) GetResult() HarvestRes_Result {
	if x != nil {
		return x.Result
	}
	return HarvestRes_Success
}

func (x *HarvestRes) GetBuild() *PlayerBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *HarvestRes) GetGoodsCount() *GoodsCount {
	if x != nil {
		return x.GoodsCount
	}
	return nil
}

type BuildStateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result BuildStateNotify_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.BuildStateNotify_Result" json:"result"`
	// @inject_tag: json:"build"
	Build *PlayerBuild `protobuf:"bytes,2,opt,name=build,proto3" json:"build"`
	// @inject_tag: json:"upgrade_goods"
	UpgradeGoods []*GoodsCount `protobuf:"bytes,3,rep,name=upgrade_goods,json=upgradeGoods,proto3" json:"upgrade_goods"` //升级所需资源
}

func (x *BuildStateNotify) Reset() {
	*x = BuildStateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildStateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStateNotify) ProtoMessage() {}

func (x *BuildStateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStateNotify.ProtoReflect.Descriptor instead.
func (*BuildStateNotify) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{18}
}

func (x *BuildStateNotify) GetResult() BuildStateNotify_Result {
	if x != nil {
		return x.Result
	}
	return BuildStateNotify_Success
}

func (x *BuildStateNotify) GetBuild() *PlayerBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *BuildStateNotify) GetUpgradeGoods() []*GoodsCount {
	if x != nil {
		return x.UpgradeGoods
	}
	return nil
}

// //////////////////////////////////////////
type PlayerBuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"build_conf_id"
	BuildConfId int32 `protobuf:"varint,2,opt,name=build_conf_id,json=buildConfId,proto3" json:"build_conf_id"`
	// @inject_tag: json:"level"
	Level int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level"`
	// @inject_tag: json:"status"
	Status PlayerBuild_Status `protobuf:"varint,4,opt,name=status,proto3,enum=pb.PlayerBuild_Status" json:"status"`
	// @inject_tag: json:"update_at"
	UpdateAt int64 `protobuf:"varint,5,opt,name=update_at,json=updateAt,proto3" json:"update_at"`
	// @inject_tag: json:"need_time"
	NeedTime int32 `protobuf:"varint,6,opt,name=need_time,json=needTime,proto3" json:"need_time"` //进入下一状态所需时长，0-表示不会变更
	// @inject_tag: json:"poses"
	Poses []int32 `protobuf:"varint,7,rep,packed,name=poses,proto3" json:"poses"`
	// @inject_tag: json:"planting"
	Planting *Planting `protobuf:"bytes,8,opt,name=planting,proto3" json:"planting"` //农作物
}

func (x *PlayerBuild) Reset() {
	*x = PlayerBuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBuild) ProtoMessage() {}

func (x *PlayerBuild) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBuild.ProtoReflect.Descriptor instead.
func (*PlayerBuild) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerBuild) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerBuild) GetBuildConfId() int32 {
	if x != nil {
		return x.BuildConfId
	}
	return 0
}

func (x *PlayerBuild) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerBuild) GetStatus() PlayerBuild_Status {
	if x != nil {
		return x.Status
	}
	return PlayerBuild_Normal
}

func (x *PlayerBuild) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *PlayerBuild) GetNeedTime() int32 {
	if x != nil {
		return x.NeedTime
	}
	return 0
}

func (x *PlayerBuild) GetPoses() []int32 {
	if x != nil {
		return x.Poses
	}
	return nil
}

func (x *PlayerBuild) GetPlanting() *Planting {
	if x != nil {
		return x.Planting
	}
	return nil
}

type Seed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"need_count"
	NeedCount int32 `protobuf:"varint,1,opt,name=need_count,json=needCount,proto3" json:"need_count"` //需要数量
	// @inject_tag: json:"goods"
	Goods *GoodsCount `protobuf:"bytes,2,opt,name=goods,proto3" json:"goods"` //种子数量
}

func (x *Seed) Reset() {
	*x = Seed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seed) ProtoMessage() {}

func (x *Seed) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seed.ProtoReflect.Descriptor instead.
func (*Seed) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{20}
}

func (x *Seed) GetNeedCount() int32 {
	if x != nil {
		return x.NeedCount
	}
	return 0
}

func (x *Seed) GetGoods() *GoodsCount {
	if x != nil {
		return x.Goods
	}
	return nil
}

type Planting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"goods_id"
	GoodsId int32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id"`
	// @inject_tag: json:"update_at"
	UpdateAt int64 `protobuf:"varint,2,opt,name=update_at,json=updateAt,proto3" json:"update_at"`
	// @inject_tag: json:"stage_time"
	StageTime int32 `protobuf:"varint,3,opt,name=stage_time,json=stageTime,proto3" json:"stage_time"`
	// @inject_tag: json:"stage"
	Stage PlantStage `protobuf:"varint,4,opt,name=stage,proto3,enum=pb.PlantStage" json:"stage"`
	// @inject_tag: json:"operate"
	Operate PlantOperate `protobuf:"varint,5,opt,name=operate,proto3,enum=pb.PlantOperate" json:"operate"`
}

func (x *Planting) Reset() {
	*x = Planting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_family_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Planting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Planting) ProtoMessage() {}

func (x *Planting) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_family_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Planting.ProtoReflect.Descriptor instead.
func (*Planting) Descriptor() ([]byte, []int) {
	return file_pb_proto_family_proto_rawDescGZIP(), []int{21}
}

func (x *Planting) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *Planting) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *Planting) GetStageTime() int32 {
	if x != nil {
		return x.StageTime
	}
	return 0
}

func (x *Planting) GetStage() PlantStage {
	if x != nil {
		return x.Stage
	}
	return PlantStage_zero
}

func (x *Planting) GetOperate() PlantOperate {
	if x != nil {
		return x.Operate
	}
	return PlantOperate_None
}

var File_pb_proto_family_proto protoreflect.FileDescriptor

var file_pb_proto_family_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x15, 0x70, 0x62, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xf3, 0x03, 0x0a, 0x09, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x3e, 0x0a, 0x10, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x48, 0x00,
	0x52, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x3b, 0x0a, 0x0f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f,
	0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x78, 0x69, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0d,
	0x65, 0x78, 0x69, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x3e, 0x0a,
	0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0e, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x3e, 0x0a,
	0x10, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0e, 0x63,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x3e, 0x0a,
	0x10, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0e, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x35, 0x0a,
	0x0d, 0x67, 0x65, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x53, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x73, 0x53, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x5f, 0x73, 0x65,
	0x65, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x48, 0x00,
	0x52, 0x0c, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x31,
	0x0a, 0x0b, 0x68, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0a, 0x68, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x22, 0xb9, 0x04, 0x0a, 0x09, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x10, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x66,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x78, 0x69, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x10, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x10, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x48, 0x00, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x65, 0x64,
	0x5f, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x73, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x67,
	0x65, 0x74, 0x73, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0e, 0x70, 0x6c,
	0x61, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x0b, 0x68, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x5f,
	0x72, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x68, 0x61, 0x72,
	0x76, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x12, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x64, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x48, 0x00, 0x52, 0x10, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x05, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x78, 0x69, 0x74, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x22, 0x60, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0d, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x0e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x73, 0x53, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x44, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0a, 0x48, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x0e,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x27, 0x0a, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x78, 0x69, 0x74,
	0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x22, 0x85, 0x02, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x25, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x33, 0x0a, 0x0d, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0c, 0x75,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x64, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x10,
	0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10,
	0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10,
	0x05, 0x22, 0xea, 0x01, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x49, 0x64, 0x12, 0x33, 0x0a, 0x0d, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0c, 0x75, 0x70, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x55, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b,
	0x4e, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x10, 0x03, 0x12, 0x0f, 0x0a,
	0x0b, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x10, 0x04, 0x22, 0xa1,
	0x01, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22,
	0x41, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x10, 0x03, 0x22, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x73, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x05,
	0x73, 0x65, 0x65, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x65, 0x64, 0x52, 0x05, 0x73, 0x65, 0x65, 0x64, 0x73, 0x22, 0xe6, 0x01, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x25,
	0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x05,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x22, 0x7e, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x4e, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x72, 0x72, 0x10, 0x02, 0x12, 0x10, 0x0a,
	0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x45, 0x72, 0x72, 0x10, 0x03, 0x12,
	0x11, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x65, 0x64, 0x45, 0x72, 0x72,
	0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x45, 0x72, 0x72, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x10, 0x06, 0x22, 0xd7, 0x01, 0x0a, 0x0a, 0x48, 0x61, 0x72, 0x76, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x72, 0x76, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x2f, 0x0a, 0x0b, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x42, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x22,
	0x89, 0x02, 0x0a, 0x10, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x12, 0x33, 0x0a, 0x0d, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0c, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x64, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x4e, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x10, 0x02, 0x12, 0x0c, 0x0a,
	0x08, 0x48, 0x61, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x4d,
	0x79, 0x73, 0x71, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x05, 0x22, 0xb3, 0x02, 0x0a, 0x0b,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05,
	0x70, 0x6f, 0x73, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x22,
	0x30, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x10,
	0x02, 0x22, 0x4b, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x65,
	0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e,
	0x65, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0xb3,
	0x01, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x67, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6c, 0x61, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x07, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x2a, 0x33, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x4f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x77, 0x6f, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x54, 0x68, 0x72, 0x65, 0x65, 0x10, 0x03, 0x2a, 0x25, 0x0a, 0x0c, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x10, 0x01,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_proto_family_proto_rawDescOnce sync.Once
	file_pb_proto_family_proto_rawDescData = file_pb_proto_family_proto_rawDesc
)

func file_pb_proto_family_proto_rawDescGZIP() []byte {
	file_pb_proto_family_proto_rawDescOnce.Do(func() {
		file_pb_proto_family_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_family_proto_rawDescData)
	})
	return file_pb_proto_family_proto_rawDescData
}

var file_pb_proto_family_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_pb_proto_family_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pb_proto_family_proto_goTypes = []interface{}{
	(PlantStage)(0),              // 0: pb.PlantStage
	(PlantOperate)(0),            // 1: pb.PlantOperate
	(CreateBuildRes_Result)(0),   // 2: pb.CreateBuildRes.Result
	(CancelBuildRes_Result)(0),   // 3: pb.CancelBuildRes.Result
	(DeleteBuildRes_Result)(0),   // 4: pb.DeleteBuildRes.Result
	(PlantSeedRes_Result)(0),     // 5: pb.PlantSeedRes.Result
	(HarvestRes_Result)(0),       // 6: pb.HarvestRes.Result
	(BuildStateNotify_Result)(0), // 7: pb.BuildStateNotify.Result
	(PlayerBuild_Status)(0),      // 8: pb.PlayerBuild.Status
	(*FamilyReq)(nil),            // 9: pb.FamilyReq
	(*FamilyRes)(nil),            // 10: pb.FamilyRes
	(*EnterFamilyReq)(nil),       // 11: pb.EnterFamilyReq
	(*ExitFamilyReq)(nil),        // 12: pb.ExitFamilyReq
	(*CreateBuildReq)(nil),       // 13: pb.CreateBuildReq
	(*CancelBuildReq)(nil),       // 14: pb.CancelBuildReq
	(*DeleteBuildReq)(nil),       // 15: pb.DeleteBuildReq
	(*GetsSeedReq)(nil),          // 16: pb.GetsSeedReq
	(*PlantSeedReq)(nil),         // 17: pb.PlantSeedReq
	(*HarvestReq)(nil),           // 18: pb.HarvestReq
	(*EnterFamilyRes)(nil),       // 19: pb.EnterFamilyRes
	(*ExitFamilyRes)(nil),        // 20: pb.ExitFamilyRes
	(*CreateBuildRes)(nil),       // 21: pb.CreateBuildRes
	(*CancelBuildRes)(nil),       // 22: pb.CancelBuildRes
	(*DeleteBuildRes)(nil),       // 23: pb.DeleteBuildRes
	(*GetsSeedRes)(nil),          // 24: pb.GetsSeedRes
	(*PlantSeedRes)(nil),         // 25: pb.PlantSeedRes
	(*HarvestRes)(nil),           // 26: pb.HarvestRes
	(*BuildStateNotify)(nil),     // 27: pb.BuildStateNotify
	(*PlayerBuild)(nil),          // 28: pb.PlayerBuild
	(*Seed)(nil),                 // 29: pb.Seed
	(*Planting)(nil),             // 30: pb.Planting
	(*GoodsCount)(nil),           // 31: pb.GoodsCount
}
var file_pb_proto_family_proto_depIdxs = []int32{
	11, // 0: pb.FamilyReq.enter_family_req:type_name -> pb.EnterFamilyReq
	12, // 1: pb.FamilyReq.exit_family_req:type_name -> pb.ExitFamilyReq
	13, // 2: pb.FamilyReq.create_build_req:type_name -> pb.CreateBuildReq
	14, // 3: pb.FamilyReq.cancel_build_req:type_name -> pb.CancelBuildReq
	15, // 4: pb.FamilyReq.delete_build_req:type_name -> pb.DeleteBuildReq
	16, // 5: pb.FamilyReq.gets_seed_req:type_name -> pb.GetsSeedReq
	17, // 6: pb.FamilyReq.plant_seed_req:type_name -> pb.PlantSeedReq
	18, // 7: pb.FamilyReq.harvest_req:type_name -> pb.HarvestReq
	19, // 8: pb.FamilyRes.enter_family_res:type_name -> pb.EnterFamilyRes
	20, // 9: pb.FamilyRes.exit_family_res:type_name -> pb.ExitFamilyRes
	21, // 10: pb.FamilyRes.create_build_res:type_name -> pb.CreateBuildRes
	22, // 11: pb.FamilyRes.cancel_build_res:type_name -> pb.CancelBuildRes
	23, // 12: pb.FamilyRes.delete_build_res:type_name -> pb.DeleteBuildRes
	24, // 13: pb.FamilyRes.gets_seed_res:type_name -> pb.GetsSeedRes
	25, // 14: pb.FamilyRes.plant_seed_res:type_name -> pb.PlantSeedRes
	26, // 15: pb.FamilyRes.harvest_res:type_name -> pb.HarvestRes
	27, // 16: pb.FamilyRes.build_state_notify:type_name -> pb.BuildStateNotify
	28, // 17: pb.EnterFamilyRes.builds:type_name -> pb.PlayerBuild
	2,  // 18: pb.CreateBuildRes.result:type_name -> pb.CreateBuildRes.Result
	28, // 19: pb.CreateBuildRes.build:type_name -> pb.PlayerBuild
	31, // 20: pb.CreateBuildRes.upgrade_goods:type_name -> pb.GoodsCount
	3,  // 21: pb.CancelBuildRes.result:type_name -> pb.CancelBuildRes.Result
	31, // 22: pb.CancelBuildRes.upgrade_goods:type_name -> pb.GoodsCount
	4,  // 23: pb.DeleteBuildRes.result:type_name -> pb.DeleteBuildRes.Result
	29, // 24: pb.GetsSeedRes.seeds:type_name -> pb.Seed
	5,  // 25: pb.PlantSeedRes.result:type_name -> pb.PlantSeedRes.Result
	28, // 26: pb.PlantSeedRes.build:type_name -> pb.PlayerBuild
	6,  // 27: pb.HarvestRes.result:type_name -> pb.HarvestRes.Result
	28, // 28: pb.HarvestRes.build:type_name -> pb.PlayerBuild
	31, // 29: pb.HarvestRes.goods_count:type_name -> pb.GoodsCount
	7,  // 30: pb.BuildStateNotify.result:type_name -> pb.BuildStateNotify.Result
	28, // 31: pb.BuildStateNotify.build:type_name -> pb.PlayerBuild
	31, // 32: pb.BuildStateNotify.upgrade_goods:type_name -> pb.GoodsCount
	8,  // 33: pb.PlayerBuild.status:type_name -> pb.PlayerBuild.Status
	30, // 34: pb.PlayerBuild.planting:type_name -> pb.Planting
	31, // 35: pb.Seed.goods:type_name -> pb.GoodsCount
	0,  // 36: pb.Planting.stage:type_name -> pb.PlantStage
	1,  // 37: pb.Planting.operate:type_name -> pb.PlantOperate
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_pb_proto_family_proto_init() }
func file_pb_proto_family_proto_init() {
	if File_pb_proto_family_proto != nil {
		return
	}
	file_pb_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_family_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterFamilyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitFamilyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsSeedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantSeedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HarvestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterFamilyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitFamilyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBuildRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBuildRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBuildRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsSeedRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantSeedRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HarvestRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildStateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_family_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Planting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_proto_family_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FamilyReq_EnterFamilyReq)(nil),
		(*FamilyReq_ExitFamilyReq)(nil),
		(*FamilyReq_CreateBuildReq)(nil),
		(*FamilyReq_CancelBuildReq)(nil),
		(*FamilyReq_DeleteBuildReq)(nil),
		(*FamilyReq_GetsSeedReq)(nil),
		(*FamilyReq_PlantSeedReq)(nil),
		(*FamilyReq_HarvestReq)(nil),
	}
	file_pb_proto_family_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FamilyRes_EnterFamilyRes)(nil),
		(*FamilyRes_ExitFamilyRes)(nil),
		(*FamilyRes_CreateBuildRes)(nil),
		(*FamilyRes_CancelBuildRes)(nil),
		(*FamilyRes_DeleteBuildRes)(nil),
		(*FamilyRes_GetsSeedRes)(nil),
		(*FamilyRes_PlantSeedRes)(nil),
		(*FamilyRes_HarvestRes)(nil),
		(*FamilyRes_BuildStateNotify)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_family_proto_rawDesc,
			NumEnums:      9,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_proto_family_proto_goTypes,
		DependencyIndexes: file_pb_proto_family_proto_depIdxs,
		EnumInfos:         file_pb_proto_family_proto_enumTypes,
		MessageInfos:      file_pb_proto_family_proto_msgTypes,
	}.Build()
	File_pb_proto_family_proto = out.File
	file_pb_proto_family_proto_rawDesc = nil
	file_pb_proto_family_proto_goTypes = nil
	file_pb_proto_family_proto_depIdxs = nil
}
