// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: pb/proto/mail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetsMailRewardsRes_Result int32

const (
	GetsMailRewardsRes_Success         GetsMailRewardsRes_Result = 0
	GetsMailRewardsRes_NoMail          GetsMailRewardsRes_Result = 1 //邮件不存在
	GetsMailRewardsRes_NoReward        GetsMailRewardsRes_Result = 2 //没有奖励
	GetsMailRewardsRes_Reward          GetsMailRewardsRes_Result = 3 //奖励已领取
	GetsMailRewardsRes_MysqlErr        GetsMailRewardsRes_Result = 4 //数据库异常
	GetsMailRewardsRes_WareHouseIsFull GetsMailRewardsRes_Result = 5 //仓库已满
)

// Enum value maps for GetsMailRewardsRes_Result.
var (
	GetsMailRewardsRes_Result_name = map[int32]string{
		0: "Success",
		1: "NoMail",
		2: "NoReward",
		3: "Reward",
		4: "MysqlErr",
		5: "WareHouseIsFull",
	}
	GetsMailRewardsRes_Result_value = map[string]int32{
		"Success":         0,
		"NoMail":          1,
		"NoReward":        2,
		"Reward":          3,
		"MysqlErr":        4,
		"WareHouseIsFull": 5,
	}
)

func (x GetsMailRewardsRes_Result) Enum() *GetsMailRewardsRes_Result {
	p := new(GetsMailRewardsRes_Result)
	*p = x
	return p
}

func (x GetsMailRewardsRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetsMailRewardsRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_mail_proto_enumTypes[0].Descriptor()
}

func (GetsMailRewardsRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_mail_proto_enumTypes[0]
}

func (x GetsMailRewardsRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetsMailRewardsRes_Result.Descriptor instead.
func (GetsMailRewardsRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{10, 0}
}

type DeleteMailRes_Result int32

const (
	DeleteMailRes_Success  DeleteMailRes_Result = 0
	DeleteMailRes_MysqlErr DeleteMailRes_Result = 1 //数据库异常
)

// Enum value maps for DeleteMailRes_Result.
var (
	DeleteMailRes_Result_name = map[int32]string{
		0: "Success",
		1: "MysqlErr",
	}
	DeleteMailRes_Result_value = map[string]int32{
		"Success":  0,
		"MysqlErr": 1,
	}
)

func (x DeleteMailRes_Result) Enum() *DeleteMailRes_Result {
	p := new(DeleteMailRes_Result)
	*p = x
	return p
}

func (x DeleteMailRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteMailRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_mail_proto_enumTypes[1].Descriptor()
}

func (DeleteMailRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_mail_proto_enumTypes[1]
}

func (x DeleteMailRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteMailRes_Result.Descriptor instead.
func (DeleteMailRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{11, 0}
}

type GetsAllMailRewardRes_Result int32

const (
	GetsAllMailRewardRes_Success         GetsAllMailRewardRes_Result = 0
	GetsAllMailRewardRes_MysqlErr        GetsAllMailRewardRes_Result = 1 //数据库异常
	GetsAllMailRewardRes_NoReward        GetsAllMailRewardRes_Result = 2 //没有奖励
	GetsAllMailRewardRes_WareHouseIsFull GetsAllMailRewardRes_Result = 3 //仓库已满
)

// Enum value maps for GetsAllMailRewardRes_Result.
var (
	GetsAllMailRewardRes_Result_name = map[int32]string{
		0: "Success",
		1: "MysqlErr",
		2: "NoReward",
		3: "WareHouseIsFull",
	}
	GetsAllMailRewardRes_Result_value = map[string]int32{
		"Success":         0,
		"MysqlErr":        1,
		"NoReward":        2,
		"WareHouseIsFull": 3,
	}
)

func (x GetsAllMailRewardRes_Result) Enum() *GetsAllMailRewardRes_Result {
	p := new(GetsAllMailRewardRes_Result)
	*p = x
	return p
}

func (x GetsAllMailRewardRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetsAllMailRewardRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_mail_proto_enumTypes[2].Descriptor()
}

func (GetsAllMailRewardRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_mail_proto_enumTypes[2]
}

func (x GetsAllMailRewardRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetsAllMailRewardRes_Result.Descriptor instead.
func (GetsAllMailRewardRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{12, 0}
}

type DeleteAllReadMailRes_Result int32

const (
	DeleteAllReadMailRes_Success  DeleteAllReadMailRes_Result = 0
	DeleteAllReadMailRes_MysqlErr DeleteAllReadMailRes_Result = 1 //数据库异常
)

// Enum value maps for DeleteAllReadMailRes_Result.
var (
	DeleteAllReadMailRes_Result_name = map[int32]string{
		0: "Success",
		1: "MysqlErr",
	}
	DeleteAllReadMailRes_Result_value = map[string]int32{
		"Success":  0,
		"MysqlErr": 1,
	}
)

func (x DeleteAllReadMailRes_Result) Enum() *DeleteAllReadMailRes_Result {
	p := new(DeleteAllReadMailRes_Result)
	*p = x
	return p
}

func (x DeleteAllReadMailRes_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteAllReadMailRes_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_mail_proto_enumTypes[3].Descriptor()
}

func (DeleteAllReadMailRes_Result) Type() protoreflect.EnumType {
	return &file_pb_proto_mail_proto_enumTypes[3]
}

func (x DeleteAllReadMailRes_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteAllReadMailRes_Result.Descriptor instead.
func (DeleteAllReadMailRes_Result) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{13, 0}
}

type Mail_Status int32

const (
	Mail_Unread   Mail_Status = 0 //未读
	Mail_UnReward Mail_Status = 1 //已读未领奖
	Mail_Reward   Mail_Status = 2 //已读已领奖
)

// Enum value maps for Mail_Status.
var (
	Mail_Status_name = map[int32]string{
		0: "Unread",
		1: "UnReward",
		2: "Reward",
	}
	Mail_Status_value = map[string]int32{
		"Unread":   0,
		"UnReward": 1,
		"Reward":   2,
	}
)

func (x Mail_Status) Enum() *Mail_Status {
	p := new(Mail_Status)
	*p = x
	return p
}

func (x Mail_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mail_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_mail_proto_enumTypes[4].Descriptor()
}

func (Mail_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_mail_proto_enumTypes[4]
}

func (x Mail_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mail_Status.Descriptor instead.
func (Mail_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{15, 0}
}

type MailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//
	//	*MailReq_GetsMailReq
	//	*MailReq_ReadMailReq
	//	*MailReq_GetsMailRewardReq
	//	*MailReq_DeleteMailReq
	//	*MailReq_GetsAllMailRewardReq
	//	*MailReq_DeleteAllReadMailReq
	Req isMailReq_Req `protobuf_oneof:"req"`
}

func (x *MailReq) Reset() {
	*x = MailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailReq) ProtoMessage() {}

func (x *MailReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailReq.ProtoReflect.Descriptor instead.
func (*MailReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (m *MailReq) GetReq() isMailReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *MailReq) GetGetsMailReq() *GetsMailReq {
	if x, ok := x.GetReq().(*MailReq_GetsMailReq); ok {
		return x.GetsMailReq
	}
	return nil
}

func (x *MailReq) GetReadMailReq() *ReadMailReq {
	if x, ok := x.GetReq().(*MailReq_ReadMailReq); ok {
		return x.ReadMailReq
	}
	return nil
}

func (x *MailReq) GetGetsMailRewardReq() *GetsMailRewardsReq {
	if x, ok := x.GetReq().(*MailReq_GetsMailRewardReq); ok {
		return x.GetsMailRewardReq
	}
	return nil
}

func (x *MailReq) GetDeleteMailReq() *DeleteMailReq {
	if x, ok := x.GetReq().(*MailReq_DeleteMailReq); ok {
		return x.DeleteMailReq
	}
	return nil
}

func (x *MailReq) GetGetsAllMailRewardReq() *GetsAllMailRewardReq {
	if x, ok := x.GetReq().(*MailReq_GetsAllMailRewardReq); ok {
		return x.GetsAllMailRewardReq
	}
	return nil
}

func (x *MailReq) GetDeleteAllReadMailReq() *DeleteAllReadMailReq {
	if x, ok := x.GetReq().(*MailReq_DeleteAllReadMailReq); ok {
		return x.DeleteAllReadMailReq
	}
	return nil
}

type isMailReq_Req interface {
	isMailReq_Req()
}

type MailReq_GetsMailReq struct {
	GetsMailReq *GetsMailReq `protobuf:"bytes,1,opt,name=gets_mail_req,json=getsMailReq,proto3,oneof"` //获取邮件列表
}

type MailReq_ReadMailReq struct {
	ReadMailReq *ReadMailReq `protobuf:"bytes,2,opt,name=read_mail_req,json=readMailReq,proto3,oneof"` //读邮件
}

type MailReq_GetsMailRewardReq struct {
	GetsMailRewardReq *GetsMailRewardsReq `protobuf:"bytes,3,opt,name=gets_mail_reward_req,json=getsMailRewardReq,proto3,oneof"` //领取奖励
}

type MailReq_DeleteMailReq struct {
	DeleteMailReq *DeleteMailReq `protobuf:"bytes,4,opt,name=delete_mail_req,json=deleteMailReq,proto3,oneof"` //删除邮件
}

type MailReq_GetsAllMailRewardReq struct {
	GetsAllMailRewardReq *GetsAllMailRewardReq `protobuf:"bytes,5,opt,name=gets_all_mail_reward_req,json=getsAllMailRewardReq,proto3,oneof"` //一键领取
}

type MailReq_DeleteAllReadMailReq struct {
	DeleteAllReadMailReq *DeleteAllReadMailReq `protobuf:"bytes,6,opt,name=delete_all_read_mail_req,json=deleteAllReadMailReq,proto3,oneof"` // 一键删除
}

func (*MailReq_GetsMailReq) isMailReq_Req() {}

func (*MailReq_ReadMailReq) isMailReq_Req() {}

func (*MailReq_GetsMailRewardReq) isMailReq_Req() {}

func (*MailReq_DeleteMailReq) isMailReq_Req() {}

func (*MailReq_GetsAllMailRewardReq) isMailReq_Req() {}

func (*MailReq_DeleteAllReadMailReq) isMailReq_Req() {}

type MailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//
	//	*MailRes_GetsMailRes
	//	*MailRes_ReadMailRes
	//	*MailRes_GetsMailRewardRes
	//	*MailRes_DeleteMailRes
	//	*MailRes_GetsAllMailRewardRes
	//	*MailRes_DeleteAllReadMailRes
	//	*MailRes_NewMailNotify
	Res isMailRes_Res `protobuf_oneof:"res"`
}

func (x *MailRes) Reset() {
	*x = MailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRes) ProtoMessage() {}

func (x *MailRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRes.ProtoReflect.Descriptor instead.
func (*MailRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (m *MailRes) GetRes() isMailRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *MailRes) GetGetsMailRes() *GetsMailRes {
	if x, ok := x.GetRes().(*MailRes_GetsMailRes); ok {
		return x.GetsMailRes
	}
	return nil
}

func (x *MailRes) GetReadMailRes() *ReadMailRes {
	if x, ok := x.GetRes().(*MailRes_ReadMailRes); ok {
		return x.ReadMailRes
	}
	return nil
}

func (x *MailRes) GetGetsMailRewardRes() *GetsMailRewardsRes {
	if x, ok := x.GetRes().(*MailRes_GetsMailRewardRes); ok {
		return x.GetsMailRewardRes
	}
	return nil
}

func (x *MailRes) GetDeleteMailRes() *DeleteMailRes {
	if x, ok := x.GetRes().(*MailRes_DeleteMailRes); ok {
		return x.DeleteMailRes
	}
	return nil
}

func (x *MailRes) GetGetsAllMailRewardRes() *GetsAllMailRewardRes {
	if x, ok := x.GetRes().(*MailRes_GetsAllMailRewardRes); ok {
		return x.GetsAllMailRewardRes
	}
	return nil
}

func (x *MailRes) GetDeleteAllReadMailRes() *DeleteAllReadMailRes {
	if x, ok := x.GetRes().(*MailRes_DeleteAllReadMailRes); ok {
		return x.DeleteAllReadMailRes
	}
	return nil
}

func (x *MailRes) GetNewMailNotify() *NewMailNotify {
	if x, ok := x.GetRes().(*MailRes_NewMailNotify); ok {
		return x.NewMailNotify
	}
	return nil
}

type isMailRes_Res interface {
	isMailRes_Res()
}

type MailRes_GetsMailRes struct {
	GetsMailRes *GetsMailRes `protobuf:"bytes,1,opt,name=gets_mail_res,json=getsMailRes,proto3,oneof"` //获取邮件列表
}

type MailRes_ReadMailRes struct {
	ReadMailRes *ReadMailRes `protobuf:"bytes,2,opt,name=read_mail_res,json=readMailRes,proto3,oneof"` //读邮件
}

type MailRes_GetsMailRewardRes struct {
	GetsMailRewardRes *GetsMailRewardsRes `protobuf:"bytes,3,opt,name=gets_mail_reward_res,json=getsMailRewardRes,proto3,oneof"` //领取奖励
}

type MailRes_DeleteMailRes struct {
	DeleteMailRes *DeleteMailRes `protobuf:"bytes,4,opt,name=delete_mail_res,json=deleteMailRes,proto3,oneof"` //删除邮件
}

type MailRes_GetsAllMailRewardRes struct {
	GetsAllMailRewardRes *GetsAllMailRewardRes `protobuf:"bytes,5,opt,name=gets_all_mail_reward_res,json=getsAllMailRewardRes,proto3,oneof"` //一键领取
}

type MailRes_DeleteAllReadMailRes struct {
	DeleteAllReadMailRes *DeleteAllReadMailRes `protobuf:"bytes,6,opt,name=delete_all_read_mail_res,json=deleteAllReadMailRes,proto3,oneof"` // 一键删除
}

type MailRes_NewMailNotify struct {
	NewMailNotify *NewMailNotify `protobuf:"bytes,100,opt,name=new_mail_notify,json=newMailNotify,proto3,oneof"` //新邮件提示
}

func (*MailRes_GetsMailRes) isMailRes_Res() {}

func (*MailRes_ReadMailRes) isMailRes_Res() {}

func (*MailRes_GetsMailRewardRes) isMailRes_Res() {}

func (*MailRes_DeleteMailRes) isMailRes_Res() {}

func (*MailRes_GetsAllMailRewardRes) isMailRes_Res() {}

func (*MailRes_DeleteAllReadMailRes) isMailRes_Res() {}

func (*MailRes_NewMailNotify) isMailRes_Res() {}

// ////////////////////////////////////////
type GetsMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
}

func (x *GetsMailReq) Reset() {
	*x = GetsMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsMailReq) ProtoMessage() {}

func (x *GetsMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsMailReq.ProtoReflect.Descriptor instead.
func (*GetsMailReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{2}
}

func (x *GetsMailReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetsMailReq) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ReadMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"mail_id"
	MailId int32 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"` //邮件Id
}

func (x *ReadMailReq) Reset() {
	*x = ReadMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailReq) ProtoMessage() {}

func (x *ReadMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailReq.ProtoReflect.Descriptor instead.
func (*ReadMailReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMailReq) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type GetsMailRewardsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"mail_id"
	MailId int32 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"` //邮件Id
}

func (x *GetsMailRewardsReq) Reset() {
	*x = GetsMailRewardsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsMailRewardsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsMailRewardsReq) ProtoMessage() {}

func (x *GetsMailRewardsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsMailRewardsReq.ProtoReflect.Descriptor instead.
func (*GetsMailRewardsReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{4}
}

func (x *GetsMailRewardsReq) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type DeleteMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"mail_id"
	MailId int32 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id"` //邮件Id
}

func (x *DeleteMailReq) Reset() {
	*x = DeleteMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMailReq) ProtoMessage() {}

func (x *DeleteMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMailReq.ProtoReflect.Descriptor instead.
func (*DeleteMailReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMailReq) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type GetsAllMailRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetsAllMailRewardReq) Reset() {
	*x = GetsAllMailRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsAllMailRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsAllMailRewardReq) ProtoMessage() {}

func (x *GetsAllMailRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsAllMailRewardReq.ProtoReflect.Descriptor instead.
func (*GetsAllMailRewardReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{6}
}

type DeleteAllReadMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAllReadMailReq) Reset() {
	*x = DeleteAllReadMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAllReadMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllReadMailReq) ProtoMessage() {}

func (x *DeleteAllReadMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllReadMailReq.ProtoReflect.Descriptor instead.
func (*DeleteAllReadMailReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{7}
}

// ///////////////////////////////////////
type GetsMailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"per_page"
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page"`
	// @inject_tag: json:"total"
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	// @inject_tag: json:"mails"
	Mails []*Mail `protobuf:"bytes,4,rep,name=mails,proto3" json:"mails"`
}

func (x *GetsMailRes) Reset() {
	*x = GetsMailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsMailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsMailRes) ProtoMessage() {}

func (x *GetsMailRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsMailRes.ProtoReflect.Descriptor instead.
func (*GetsMailRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{8}
}

func (x *GetsMailRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetsMailRes) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetsMailRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetsMailRes) GetMails() []*Mail {
	if x != nil {
		return x.Mails
	}
	return nil
}

type ReadMailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"mail"
	Mail *Mail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail"`
	// @inject_tag: json:"content"
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	// @inject_tag: json:"rewards"
	Rewards []*GoodsCount `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards"`
}

func (x *ReadMailRes) Reset() {
	*x = ReadMailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailRes) ProtoMessage() {}

func (x *ReadMailRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailRes.ProtoReflect.Descriptor instead.
func (*ReadMailRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{9}
}

func (x *ReadMailRes) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *ReadMailRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReadMailRes) GetRewards() []*GoodsCount {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type GetsMailRewardsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result GetsMailRewardsRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.GetsMailRewardsRes_Result" json:"result"`
	// @inject_tag: json:"mail"
	Mail *Mail `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail"`
	// @inject_tag: json:"rewards"
	Rewards []*GoodsCount `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards"`
}

func (x *GetsMailRewardsRes) Reset() {
	*x = GetsMailRewardsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsMailRewardsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsMailRewardsRes) ProtoMessage() {}

func (x *GetsMailRewardsRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsMailRewardsRes.ProtoReflect.Descriptor instead.
func (*GetsMailRewardsRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{10}
}

func (x *GetsMailRewardsRes) GetResult() GetsMailRewardsRes_Result {
	if x != nil {
		return x.Result
	}
	return GetsMailRewardsRes_Success
}

func (x *GetsMailRewardsRes) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *GetsMailRewardsRes) GetRewards() []*GoodsCount {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type DeleteMailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result DeleteMailRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.DeleteMailRes_Result" json:"result"`
}

func (x *DeleteMailRes) Reset() {
	*x = DeleteMailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMailRes) ProtoMessage() {}

func (x *DeleteMailRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMailRes.ProtoReflect.Descriptor instead.
func (*DeleteMailRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMailRes) GetResult() DeleteMailRes_Result {
	if x != nil {
		return x.Result
	}
	return DeleteMailRes_Success
}

type GetsAllMailRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result GetsAllMailRewardRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.GetsAllMailRewardRes_Result" json:"result"`
	// @inject_tag: json:"rewards"
	Rewards []*GoodsCount `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards"`
}

func (x *GetsAllMailRewardRes) Reset() {
	*x = GetsAllMailRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsAllMailRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsAllMailRewardRes) ProtoMessage() {}

func (x *GetsAllMailRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsAllMailRewardRes.ProtoReflect.Descriptor instead.
func (*GetsAllMailRewardRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{12}
}

func (x *GetsAllMailRewardRes) GetResult() GetsAllMailRewardRes_Result {
	if x != nil {
		return x.Result
	}
	return GetsAllMailRewardRes_Success
}

func (x *GetsAllMailRewardRes) GetRewards() []*GoodsCount {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type DeleteAllReadMailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"result"
	Result DeleteAllReadMailRes_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.DeleteAllReadMailRes_Result" json:"result"`
}

func (x *DeleteAllReadMailRes) Reset() {
	*x = DeleteAllReadMailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAllReadMailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllReadMailRes) ProtoMessage() {}

func (x *DeleteAllReadMailRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllReadMailRes.ProtoReflect.Descriptor instead.
func (*DeleteAllReadMailRes) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAllReadMailRes) GetResult() DeleteAllReadMailRes_Result {
	if x != nil {
		return x.Result
	}
	return DeleteAllReadMailRes_Success
}

type NewMailNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewMailNotify) Reset() {
	*x = NewMailNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewMailNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMailNotify) ProtoMessage() {}

func (x *NewMailNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMailNotify.ProtoReflect.Descriptor instead.
func (*NewMailNotify) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{14}
}

// ///////////////////////////////////////
type Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"title"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	// @inject_tag: json:"sender"
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender"`
	// @inject_tag: json:"status"
	Status Mail_Status `protobuf:"varint,4,opt,name=status,proto3,enum=pb.Mail_Status" json:"status"`
	// @inject_tag: json:"create_at"
	CreateAt int64 `protobuf:"varint,5,opt,name=create_at,json=createAt,proto3" json:"create_at"` //创建时间
}

func (x *Mail) Reset() {
	*x = Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_mail_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_mail_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_pb_proto_mail_proto_rawDescGZIP(), []int{15}
}

func (x *Mail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mail) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Mail) GetStatus() Mail_Status {
	if x != nil {
		return x.Status
	}
	return Mail_Unread
}

func (x *Mail) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

var File_pb_proto_mail_proto protoreflect.FileDescriptor

var file_pb_proto_mail_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x15, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xae, 0x03, 0x0a, 0x07, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x35, 0x0a, 0x0d,
	0x67, 0x65, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x35, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x61, 0x69, 0x6c,
	0x5f, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x72,
	0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x49, 0x0a, 0x14, 0x67, 0x65,
	0x74, 0x73, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x72,
	0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x11, 0x67, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x3b, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x52, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x41, 0x6c,
	0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x48, 0x00,
	0x52, 0x14, 0x67, 0x65, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x52, 0x0a, 0x18, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72,
	0x65, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x14, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65,
	0x71, 0x22, 0xeb, 0x03, 0x0a, 0x07, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a,
	0x0d, 0x67, 0x65, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x61, 0x69,
	0x6c, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x72, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x14, 0x67,
	0x65, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f,
	0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x48, 0x00, 0x52, 0x11, 0x67, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x5f,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x41,
	0x6c, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x14, 0x67, 0x65, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x18, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f,
	0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x14, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0f, 0x6e,
	0x65, 0x77, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x64,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x69,
	0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x4d, 0x61,
	0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x22,
	0x3c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a,
	0x0b, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x16,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x72,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x6d, 0x61, 0x69,
	0x6c, 0x73, 0x22, 0x6f, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x22, 0xf3, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1c, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x28, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0x5e, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x4d, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x4e, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45,
	0x72, 0x72, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x65, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x49, 0x73, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x05, 0x22, 0x66, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x23, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45, 0x72, 0x72, 0x10,
	0x01, 0x22, 0xc1, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0x46, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45, 0x72, 0x72,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x10, 0x02,
	0x12, 0x13, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x73, 0x46,
	0x75, 0x6c, 0x6c, 0x10, 0x03, 0x22, 0x74, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x61, 0x64,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x23, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x45, 0x72, 0x72, 0x10, 0x01, 0x22, 0x0f, 0x0a, 0x0d, 0x4e,
	0x65, 0x77, 0x4d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0xba, 0x01, 0x0a,
	0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x55, 0x6e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_mail_proto_rawDescOnce sync.Once
	file_pb_proto_mail_proto_rawDescData = file_pb_proto_mail_proto_rawDesc
)

func file_pb_proto_mail_proto_rawDescGZIP() []byte {
	file_pb_proto_mail_proto_rawDescOnce.Do(func() {
		file_pb_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_mail_proto_rawDescData)
	})
	return file_pb_proto_mail_proto_rawDescData
}

var file_pb_proto_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pb_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pb_proto_mail_proto_goTypes = []interface{}{
	(GetsMailRewardsRes_Result)(0),   // 0: pb.GetsMailRewardsRes.Result
	(DeleteMailRes_Result)(0),        // 1: pb.DeleteMailRes.Result
	(GetsAllMailRewardRes_Result)(0), // 2: pb.GetsAllMailRewardRes.Result
	(DeleteAllReadMailRes_Result)(0), // 3: pb.DeleteAllReadMailRes.Result
	(Mail_Status)(0),                 // 4: pb.Mail.Status
	(*MailReq)(nil),                  // 5: pb.MailReq
	(*MailRes)(nil),                  // 6: pb.MailRes
	(*GetsMailReq)(nil),              // 7: pb.GetsMailReq
	(*ReadMailReq)(nil),              // 8: pb.ReadMailReq
	(*GetsMailRewardsReq)(nil),       // 9: pb.GetsMailRewardsReq
	(*DeleteMailReq)(nil),            // 10: pb.DeleteMailReq
	(*GetsAllMailRewardReq)(nil),     // 11: pb.GetsAllMailRewardReq
	(*DeleteAllReadMailReq)(nil),     // 12: pb.DeleteAllReadMailReq
	(*GetsMailRes)(nil),              // 13: pb.GetsMailRes
	(*ReadMailRes)(nil),              // 14: pb.ReadMailRes
	(*GetsMailRewardsRes)(nil),       // 15: pb.GetsMailRewardsRes
	(*DeleteMailRes)(nil),            // 16: pb.DeleteMailRes
	(*GetsAllMailRewardRes)(nil),     // 17: pb.GetsAllMailRewardRes
	(*DeleteAllReadMailRes)(nil),     // 18: pb.DeleteAllReadMailRes
	(*NewMailNotify)(nil),            // 19: pb.NewMailNotify
	(*Mail)(nil),                     // 20: pb.Mail
	(*GoodsCount)(nil),               // 21: pb.GoodsCount
}
var file_pb_proto_mail_proto_depIdxs = []int32{
	7,  // 0: pb.MailReq.gets_mail_req:type_name -> pb.GetsMailReq
	8,  // 1: pb.MailReq.read_mail_req:type_name -> pb.ReadMailReq
	9,  // 2: pb.MailReq.gets_mail_reward_req:type_name -> pb.GetsMailRewardsReq
	10, // 3: pb.MailReq.delete_mail_req:type_name -> pb.DeleteMailReq
	11, // 4: pb.MailReq.gets_all_mail_reward_req:type_name -> pb.GetsAllMailRewardReq
	12, // 5: pb.MailReq.delete_all_read_mail_req:type_name -> pb.DeleteAllReadMailReq
	13, // 6: pb.MailRes.gets_mail_res:type_name -> pb.GetsMailRes
	14, // 7: pb.MailRes.read_mail_res:type_name -> pb.ReadMailRes
	15, // 8: pb.MailRes.gets_mail_reward_res:type_name -> pb.GetsMailRewardsRes
	16, // 9: pb.MailRes.delete_mail_res:type_name -> pb.DeleteMailRes
	17, // 10: pb.MailRes.gets_all_mail_reward_res:type_name -> pb.GetsAllMailRewardRes
	18, // 11: pb.MailRes.delete_all_read_mail_res:type_name -> pb.DeleteAllReadMailRes
	19, // 12: pb.MailRes.new_mail_notify:type_name -> pb.NewMailNotify
	20, // 13: pb.GetsMailRes.mails:type_name -> pb.Mail
	20, // 14: pb.ReadMailRes.mail:type_name -> pb.Mail
	21, // 15: pb.ReadMailRes.rewards:type_name -> pb.GoodsCount
	0,  // 16: pb.GetsMailRewardsRes.result:type_name -> pb.GetsMailRewardsRes.Result
	20, // 17: pb.GetsMailRewardsRes.mail:type_name -> pb.Mail
	21, // 18: pb.GetsMailRewardsRes.rewards:type_name -> pb.GoodsCount
	1,  // 19: pb.DeleteMailRes.result:type_name -> pb.DeleteMailRes.Result
	2,  // 20: pb.GetsAllMailRewardRes.result:type_name -> pb.GetsAllMailRewardRes.Result
	21, // 21: pb.GetsAllMailRewardRes.rewards:type_name -> pb.GoodsCount
	3,  // 22: pb.DeleteAllReadMailRes.result:type_name -> pb.DeleteAllReadMailRes.Result
	4,  // 23: pb.Mail.status:type_name -> pb.Mail.Status
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pb_proto_mail_proto_init() }
func file_pb_proto_mail_proto_init() {
	if File_pb_proto_mail_proto != nil {
		return
	}
	file_pb_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsMailRewardsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsAllMailRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAllReadMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsMailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsMailRewardsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsAllMailRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAllReadMailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewMailNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_mail_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_proto_mail_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MailReq_GetsMailReq)(nil),
		(*MailReq_ReadMailReq)(nil),
		(*MailReq_GetsMailRewardReq)(nil),
		(*MailReq_DeleteMailReq)(nil),
		(*MailReq_GetsAllMailRewardReq)(nil),
		(*MailReq_DeleteAllReadMailReq)(nil),
	}
	file_pb_proto_mail_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*MailRes_GetsMailRes)(nil),
		(*MailRes_ReadMailRes)(nil),
		(*MailRes_GetsMailRewardRes)(nil),
		(*MailRes_DeleteMailRes)(nil),
		(*MailRes_GetsAllMailRewardRes)(nil),
		(*MailRes_DeleteAllReadMailRes)(nil),
		(*MailRes_NewMailNotify)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_mail_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_proto_mail_proto_goTypes,
		DependencyIndexes: file_pb_proto_mail_proto_depIdxs,
		EnumInfos:         file_pb_proto_mail_proto_enumTypes,
		MessageInfos:      file_pb_proto_mail_proto_msgTypes,
	}.Build()
	File_pb_proto_mail_proto = out.File
	file_pb_proto_mail_proto_rawDesc = nil
	file_pb_proto_mail_proto_goTypes = nil
	file_pb_proto_mail_proto_depIdxs = nil
}
